import { useState } from "react";
import type { AmountRecord, Budget } from "@/lib/planning/budget-types";
import { AMOUNT_STAGES, VAT } from "@/lib/planning/budget-types";
import { newAmountRecord, scopeKey } from "@/lib/planning/budget-model";
import { recordWon, money } from "@/lib/planning/budget-math";
import { validateBudget } from "@/lib/planning/budget-validation";
import type { Option, PlanDraft } from "@/lib/planning/types";
import { Field, Select } from "../Fields";
import { Check, ScopeFields } from "./Fields";

export function AmountRecordsView({ budget: b }: { budget: Budget }) {
  return <div className="space-y-3"><p className="text-sm leading-6 text-muted">원문 단계별 금액입니다. 아래 기록은 지출 산출에 더하지 않으며, 서로 다른 단계와 개별·누계를 합산하지 않습니다.</p>{b.records.map(r => <article key={r.id} className="rounded-xl border border-ink/15 p-4 text-sm leading-7"><h4 className="font-bold">{r.recorded ? "기록됨" : "작성 중"} · {r.name || "이름 미정"} · {AMOUNT_STAGES[r.stage]} · {r.kind === "cumulative" ? "누계" : "개별"}</h4><p>원문 {r.original || "빈칸"} {r.unit === "won" ? "원" : r.unit === "thousandWon" ? "천원" : "단위 미확인"} · 통화 {r.currency || "미확인"}<br />원 환산 {money(recordWon(r.original, r.unit, r.currency))} · {VAT[r.vat]}</p><p>범위 {r.scope.kind === "whole" ? "전체 행사" : r.scope.kind === "partial" ? "부분 업무" : "미확인"} · {r.scope.name || "미정"}<br />포함 {r.scope.includes || "미정"} / 제외 {r.scope.excludes || "미정"} / 부서 {r.scope.departments || "미확인"}<br />기간 {r.period.start || "미정"} ~ {r.period.end || "미정"}</p><p className="whitespace-pre-wrap break-words">출처 {r.reference} · 페이지 {r.page || "미정"} · 기준일 {r.asOf}</p>{r.missingReason && <p>미환산·결측 이유: {r.missingReason}</p>}{r.includesIds.length > 0 && <p>포함 기록: {r.includesIds.map(id => b.records.find(x => x.id === id)?.name || id).join(" · ")}</p>}{(r.basis !== b.basis || scopeKey(r.scope) !== scopeKey(b.scope)) && <p className="font-bold text-coral">이전 조건·다른 범위의 기록 · 현재 기획의 확정 금액으로 적용하지 않음</p>}</article>)}{!b.records.length && <p className="text-sm text-muted">단계별 원문 기록이 없습니다.</p>}</div>;
}
export function BudgetRecords({ budget: b, draft: d, option: o, change }: { budget: Budget; draft: PlanDraft; option: Option; change: (b: Budget) => void }) {
  const [error, setError] = useState("");
  const r = b.records.find(r => !r.recorded) ?? null;
  const set = (patch: Partial<AmountRecord>) => { if (r) change({ ...b, records: b.records.map(x => x.id === r.id ? { ...r, ...patch } : x) }); setError(""); };
  return <details className="region-card"><summary className="cursor-pointer text-xl font-extrabold">단계별 원문 금액 · {b.records.length}건</summary><div className="mt-4 space-y-4"><AmountRecordsView budget={b} /><button className="region-button" disabled={b.records.length >= 100 || !!r} onClick={() => { change({ ...b, records: [...b.records, newAmountRecord(b)] }); setError(""); }}>새 원문 기록 작성</button>
    {r && <fieldset className="min-w-0 space-y-4 rounded-xl bg-paper p-4"><legend className="font-bold">추가할 원문 금액</legend><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
      <Field label="금액 기록 이름" value={r.name} onChange={name => set({ name })} /><Select label="원문 금액 단계" value={r.stage} onChange={stage => set({ stage: stage as AmountRecord["stage"] })} options={AMOUNT_STAGES} /><Select label="개별·누계 구분" value={r.kind} onChange={kind => set({ kind: kind as AmountRecord["kind"], includesIds: [] })} options={{ individual: "개별 기록", cumulative: "누계 기록" }} />
      <Field label="원문 금액 표기" value={r.original} onChange={original => set({ original })} /><Select label="원문 금액 단위" value={r.unit} onChange={unit => set({ unit: unit as AmountRecord["unit"] })} options={{ unknown: "미확인", won: "원", thousandWon: "천원" }} /><Field label="원문 통화" value={r.currency} onChange={currency => set({ currency })} />
      <Select label="원문 세금 기준" value={r.vat} onChange={vat => set({ vat: vat as AmountRecord["vat"] })} options={VAT} /><Field label="원문 출처·문서" value={r.reference} onChange={reference => set({ reference })} /><Field label="원문 페이지" value={r.page} onChange={page => set({ page })} /><Field label="원문 기준일" type="date" value={r.asOf} onChange={asOf => set({ asOf })} />
      <Field label="원문 적용 시작일" type="date" value={r.period.start} onChange={start => set({ period: { ...r.period, start } })} /><Field label="원문 적용 종료일" type="date" value={r.period.end} onChange={end => set({ period: { ...r.period, end } })} /><Field label="결측·미환산 이유" value={r.missingReason} onChange={missingReason => set({ missingReason })} />
    </div><ScopeFields prefix="원문 " scope={r.scope} change={scope => set({ scope })} />{r.kind === "cumulative" && <div className="space-y-2"><p className="font-bold">이 누계에 포함된 기존 기록</p>{b.records.filter(old => old.recorded).map(old => <Check key={old.id} label={`${AMOUNT_STAGES[old.stage]} · ${old.name}`} checked={r.includesIds.includes(old.id)} onChange={yes => set({ includesIds: yes ? [...r.includesIds, old.id] : r.includesIds.filter(id => id !== old.id) })} />)}</div>}
    {error && <p role="alert" className="text-sm text-coral">{error}</p>}<button className="region-primary" onClick={() => { try { const next = { ...b, records: b.records.map(x => x.id === r.id ? { ...r, recorded: true } : x) }; validateBudget(next, d, o); change(next); } catch (e) { setError((e as Error).message); } }}>원문 금액 기록 추가</button><button className="region-button ml-2" onClick={() => change({ ...b, records: b.records.filter(x => x.id !== r.id) })}>작성 중 원문 입력 제외</button><p className="text-xs text-muted">원/천원·KRW가 확인된 숫자만 환산합니다. '-', 미공개 등 원문은 이유와 함께 보존하며 0원으로 바꾸지 않습니다. 정정은 새 기록으로 남기세요.</p></fieldset>}
  </div></details>;
}
