apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fest-compass

resources:
  - ../../base
  - namespace.yaml
  - httproute.yaml

images:
  - name: registry.damecasol.com/fest-compass/web
    newName: registry.damecasol.com/fest-compass/web
    digest: sha256:cfd5952966b2549b06f3c5855705f45a8e311a3b419fa9e418fa8c8d5d6e2371

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: fest-compass
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations
        value:
          observability.damecasol.com/service-version: sha256:cfd5952966b2549b06f3c5855705f45a8e311a3b419fa9e418fa8c8d5d6e2371
