apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fest-compass

resources:
  - ../../base
  - namespace.yaml
  - httproute.yaml

images:
  - name: registry.damecasol.com/fest-compass/web
    newName: registry.damecasol.com/fest-compass/web
    digest: sha256:4e1f2992616bd3963021838ac0c42677c98eb1d92451491d4c8140a131085351

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: fest-compass
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations
        value:
          observability.damecasol.com/service-version: sha256:4e1f2992616bd3963021838ac0c42677c98eb1d92451491d4c8140a131085351
