apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fest-compass

resources:
  - ../../base
  - namespace.yaml
  - httproute.yaml

images:
  - name: registry.damecasol.com/fest-compass/web
    newName: registry.damecasol.com/fest-compass/web
    digest: sha256:32db6593000e16a2f7b4fce6817417be6d49d3279909130a211db74f10ba9c4d

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: fest-compass
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations
        value:
          observability.damecasol.com/service-version: sha256:32db6593000e16a2f7b4fce6817417be6d49d3279909130a211db74f10ba9c4d
