import assert from 'node:assert/strict';
import {mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {chromium} from 'playwright';
const base=process.env.E2E_BASE_URL;if(!base)throw new Error('E2E_BASE_URL required');
const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1440,height:1100},locale:'ko-KR'}),page=await context.newPage();
page.setDefaultTimeout(15000);
const errors=[],writes=[],requests=[],passed=[];let shifted=false;
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(new URL(r.url()).origin===new URL(base).origin&&!['GET','HEAD'].includes(r.method())&&!r.url().includes('/cdn-cgi/'))writes.push(r.url());});
await context.route('**/api/regions?*',async route=>{
 const q=Object.fromEntries(new URL(route.request().url()).searchParams);requests.push(q);
 const items=[['1','기준 행사 (가상)',shifted?38:36,127],['2','가까운 행사 (가상)',36.1,127],['3','먼 행사 (가상)',37,127],['4','좌표 없는 행사 (가상)',null,null]].map(([id,title,latitude,longitude])=>({id,title,latitude,longitude,start:'2026-09-01',end:'2026-09-30',address:'가상 주소',modifiedAt:null}));
 await route.fulfill({json:{query:q,region:{provinceCode:q.province,districtCode:q.district,provinceName:'충청남도',districtName:'공주시'},resources:{status:'complete',message:'전체 페이지 확인 완료 (가상)',items,total:4,pages:1,collectedAt:shifted?'2026-09-11T00:00:00Z':'2026-09-10T00:00:00Z',source:'https://www.data.go.kr/data/15101578/openapi.do'},history:{status:'unavailable',points:[]}}});
});
const button=name=>page.getByRole('button',{name,exact:true}),found=page.getByRole('region',{name:'회차 검색 결과'}),chart=found.getByRole('region',{name:'기준 행사와 직선거리'});
const anchor=page.getByLabel('거리 기준 행사',{exact:true}),radius=page.getByLabel('직선거리 반경',{exact:true}),id=n=>`current-${n}-2026-09-01-2026-09-30`;
async function open(){await page.goto(`${base}/compare?province=44&district=150&mode=current&start=2026-09-05&end=2026-09-06`);const reject=page.getByRole('button',{name:/^(Reject All|모두 거부|Reject all)$/});if(await reject.isVisible())await reject.click();await found.getByRole('heading',{name:'현재 조회한 등록 행사 · 4건',exact:true}).waitFor();await page.getByText('등록 행사의 전체 페이지를 지역별로 조회하고 있습니다…',{exact:true}).waitFor({state:'hidden'});}
try{
 mkdirSync('output/playwright',{recursive:true});await open();assert.equal(await anchor.locator('option').count(),4);assert.equal(await chart.count(),0);passed.push('only-located-current-events-can-be-anchors');
 const before=requests.length;await anchor.selectOption(id(1));await chart.getByText('직선거리 약 11.1km',{exact:true}).waitFor();assert.deepEqual(await found.locator('article h3').allTextContents(),['기준 행사 (가상)','가까운 행사 (가상)','먼 행사 (가상)','좌표 없는 행사 (가상)']);passed.push('distance-order-and-numeric-chart');
 await radius.selectOption('10');await chart.getByText('거리 확인 1건 · 거리 미확인 1건 · 반경 밖 2건 제외',{exact:true}).waitFor();assert.equal(await found.locator('article').count(),2);await found.locator('article').filter({hasText:'좌표 없는 행사 (가상)'}).getByText('거리 미확인 · 반경 포함 여부 미확인',{exact:true}).waitFor();passed.push('radius-keeps-unknown-separate');
 await radius.selectOption('30');await button('2026 가까운 행사 (가상) 비교에 추가').click();assert.equal(requests.length,before);passed.push('distance-controls-make-no-additional-api-calls');
 await anchor.selectOption(id(3));await button('선택 회차와 비교 조건 담기').click();await page.getByText(/축제 비교를 기획 근거에 담았습니다/).waitFor();const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('fest-compass.comparison-evidence.v1')).items[0]);assert.equal(saved.context.distance.anchor.editionId,id(3));assert.equal(saved.editions[0].discoveredWith.distance.anchor.editionId,id(1));assert.equal(saved.editions[0].point.latitude,36.1);passed.push('selected-original-anchor-survives-new-reference');
 await page.goto(`${base}/evidence#comparisons`);const pending=page.waitForEvent('download');await button('비교 근거 파일 보관').click();const raw=readFileSync(await (await pending).path(),'utf8');assert.equal(JSON.parse(raw).items[0].editions[0].discoveredWith.distance.radiusKm,30);await page.evaluate(()=>localStorage.removeItem('fest-compass.comparison-evidence.v1'));await page.reload();await page.getByLabel('비교 근거 파일 가져오기').setInputFiles({name:'distance.json',mimeType:'application/json',buffer:Buffer.from(raw)});await page.getByText('당시 비교 그래프·수치·출처 보기',{exact:true}).click();await page.getByText('직선거리 약 11.1km',{exact:true}).waitFor();passed.push('download-import-original-distance-chart');
 await page.getByRole('link',{name:'이 비교 근거로 후보 기획 →',exact:true}).click();await page.getByText('연결 전 당시 값·출처 확인',{exact:true}).click();await page.getByText('직선거리 약 11.1km',{exact:true}).waitFor();passed.push('planning-keeps-distance-snapshot');
 await open();await anchor.selectOption(id(1));shifted=true;const response=page.waitForResponse(r=>r.url().includes('/api/regions?'));await button('등록 행사 조회').click();await response;await chart.getByText('직선거리 약 11.1km',{exact:true}).waitFor();await chart.getByText('거리 기준 좌표·출처 확인',{exact:true}).click();await chart.getByText(/위도 36 · 경도 127/).waitFor();passed.push('requery-does-not-replace-anchor-snapshot');
 await anchor.selectOption('');assert.equal(await chart.count(),0);await button('출처가 있는 과거 회차').click();assert.equal(await anchor.count(),0);passed.push('clear-and-archive-remove-distance-controls');
 shifted=false;await open();await anchor.selectOption(id(1));await radius.selectOption('30');await page.screenshot({path:'output/playwright/distance-desktop-test.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);await page.screenshot({path:'output/playwright/distance-mobile-test.png',fullPage:true});passed.push('390px-distance-chart');
 assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);const report={checkedAt:new Date().toISOString(),headless:true,data:'synthetic registered festivals and coordinates',passed,errors,writes};writeFileSync('output/playwright/distance-result.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}catch(e){console.error(JSON.stringify({passed,requests,errors,error:String(e)}));await page.screenshot({path:'output/playwright/distance-failure.png',fullPage:true});throw e;}finally{await browser.close();}
