import assert from "node:assert/strict";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { chromium } from "playwright";
import { mockMapTiles } from "./map-test-tiles.mjs";

const base = process.env.E2E_BASE_URL || "http://127.0.0.1:3112", key = "fest-compass.planning.v1";
const browser = await chromium.launch({ headless: true }), context = await browser.newContext({ viewport: { width: 1440, height: 1000 } }), page = await context.newPage();
await mockMapTiles(context);
const errors = [], writes = [], passed = [];
const watch = p => { p.on("pageerror", e => errors.push(e.message)); p.on("console", m => { if (m.type() === "error") errors.push(m.text()); }); p.on("request", r => { if (r.url().startsWith(base) && r.method() !== "GET") writes.push(r.method()); }); };
watch(page);
const visible = locator => locator.waitFor({ state: "visible" });
const button = name => page.getByRole("button", { name, exact: true });
const field = label => page.getByLabel(label, { exact: true });
const data = () => page.evaluate(k => JSON.parse(localStorage.getItem(k)), key);
const save = async () => { await button("초안 저장").click(); await visible(page.getByText("이 브라우저에 초안을 저장했습니다.", { exact: true })); };
try {
  await page.goto(`${base}/compare`); await button("논산 3회차 방문 비교").click();
  await field("선택 시작").selectOption("0"); await field("선택 끝").selectOption("0"); await button("선택한 방문 추세 담기").click();
  await visible(page.getByText(/축제 비교를 기획 근거에 담았습니다/));
  await page.goto(`${base}/evidence#comparisons`); await page.getByRole("link", { name: "이 비교 근거로 후보 기획 →", exact: true }).click();
  await field("기획 이름").fill("2027 축제 후보 검증"); await field("사업연도").fill("2027"); await field("기획 담당 지역").selectOption("44/150");
  await field("후보 이름").fill("봄꽃 산책"); await field("주제").fill("지역 자연"); await field("아이템·프로그램").fill("꽃길 산책과 지역 해설"); await field("참여 대상").fill("가족"); await field("후보 장소·주소").fill("검증 장소 A"); await field("담당자 가정").fill("가족 참여를 기대하는 검증용 가정");
  await field("근거를 적용할 판단").selectOption("timing"); await field("이 자료를 참고하는 판단 이유").fill("타 지역의 개최 시작일 추세를 참고하되 입장객으로 해석하지 않음"); await button("선택한 근거 연결").click();
  await visible(page.getByText(/시기 · 2023 논산딸기축제/)); await button("선택한 근거 연결").click(); await visible(page.getByRole("alert").filter({ hasText: "이미 연결" }));
  passed.push("real-comparison-deep-link", "evidence-and-judgment-separated", "duplicate-link-preserved");
  await page.getByText("사업 정보와 수행 관계", { exact: true }).click(); await field("담당 부서").fill("관광부서"); await field("신규·계속 여부").selectOption("continuing"); await field("사업 목적").fill("지역 자원 기반 기획 검증");
  await button("수행 관계 추가").click(); await field("수행 조직·역할").fill("검증 문화재단"); await field("수행 관계").selectOption("foundation"); await button("수행 관계 추가").click(); await field("수행 조직·역할").nth(1).fill("검증 무대업체"); await field("수행 관계").nth(1).selectOption("service");
  await page.getByText("장소와 기간별 확인", { exact: true }).click();
  for (const [label, value] of [["설치 시작일", "2027-04-09"], ["설치 종료일", "2027-04-09"], ["행사 시작일", "2027-04-10"], ["행사 종료일", "2027-04-08"], ["철거 시작일", "2027-04-12"], ["철거 종료일", "2027-04-12"]]) await field(label).fill(value);
  await button("초안 저장").click(); await visible(page.getByRole("alert").filter({ hasText: "종료일" })); assert.equal(await data(), null);
  await field("행사 종료일").fill("2027-04-11"); await field("장소 확인 상태").selectOption("available"); await button("장소 확인 기록 추가").click(); await visible(page.getByRole("alert").filter({ hasText: "확인에는" }));
  await field("장소 확인 조직·역할").fill("시설 관리 담당"); await field("장소 확인일").fill("2026-09-08"); await field("장소 확인 참조").fill("행사 기간 대관 회신 검증 메모"); await button("장소 확인 기록 추가").click();
  await save(); let p = await data(); assert.deepEqual(p.draft.relations.map(r => r.relation), ["foundation", "service"]); assert.equal(p.draft.regionKey, "44/150"); assert.equal(p.draft.options[0].venueChecks.length, 1); assert.equal(p.draft.options[0].venueChecks[0].stage, "event");
  passed.push("owner-region-independent", "multiple-delivery-relations", "invalid-date-keeps-storage", "venue-confirmation-requires-basis", "three-stage-confirmations-independent");
  await page.getByText("준비 과제 0개", { exact: true }).click(); await button("준비 과제 추가").click(); await field("과제 이름").fill("장소 확인"); await field("과제 담당 조직·역할").fill("시설 담당"); await field("과제 기한").fill("2027-03-01"); await field("자료 식별·참조 메모").fill("견적 참조만 추가한 상태"); await save();
  assert.equal((await data()).draft.options[0].tasks[0].progress, "todo"); assert.deepEqual((await data()).draft.options[0].tasks[0].reviews, []);
  await field("과제 진행").selectOption("done"); await button("준비 과제 추가").click(); await field("과제 이름").nth(1).fill("계약 자료 준비"); await page.getByRole("checkbox", { name: "장소 확인", exact: true }).check();
  await page.getByRole("checkbox", { name: "계약 자료 준비", exact: true }).check(); await button("초안 저장").click(); await visible(page.getByRole("alert").filter({ hasText: "순환" })); await page.getByRole("checkbox", { name: "계약 자료 준비", exact: true }).uncheck();
  await field("과제 진행").nth(0).selectOption("todo"); await field("과제 진행").nth(1).selectOption("doing"); await button("초안 저장").click(); await visible(page.getByRole("alert").filter({ hasText: "예외 진행" })); await field("선행 미완료 시 예외 진행 이유").nth(1).fill("문서 초안은 병행 준비 가능"); await save();
  await field("과제 적용 여부").nth(1).selectOption("no"); await button("초안 저장").click(); await visible(page.getByRole("alert").filter({ hasText: "사유와 판단일" })); await field("해당 없음 사유").fill("시험에서 계약 집행 대상 아님"); await field("해당 없음 판단일").fill("2026-09-08");
  await page.getByText("외부 확인 기록 · 현재 미확인", { exact: true }).first().click(); await field("외부 확인 상태").first().selectOption("confirmed"); await field("외부 확인 조직·역할").first().fill("대관 담당"); await field("외부 확인 참조").first().fill("회신 검증 메모"); await button("외부 확인 기록 추가").first().click(); await save();
  passed.push("reference-is-not-completion", "cycle-rejected", "dependency-exception-reason", "not-applicable-requires-reason-date", "external-review-independent");
  await button("현재 후보 복사").click(); await field("후보 이름").fill("지역 먹거리 체험"); await field("아이템·프로그램").fill("농산물 체험 부스"); await field("후보 장소·주소").fill("검증 장소 B"); await field("후보 판단").selectOption("excluded"); await field("선택·제외 이유").fill("대관과 준비 범위 미확인으로 이번 안에서 제외"); await save();
  p = await data(); assert.equal(p.draft.options.length, 2); assert.equal(p.draft.options[1].venueChecks.length, 0); assert.equal(p.draft.options[1].tasks[0].due, ""); assert.equal(p.draft.options[1].tasks[0].reviews.length, 0);
  await button("봄꽃 산책").click(); await field("후보 판단").selectOption("selected"); await field("선택·제외 이유").fill("지역 자원 활용을 우선 검토하되 설치·철거 사용은 추가 확인");
  await button("같은 항목으로 비교").click(); await visible(page.getByRole("heading", { name: "기획 후보 비교", exact: true })); await visible(page.getByRole("img", { name: "같은 날짜 축의 후보별 설치·행사·철거 일정", exact: true })); await field("보관 메모").fill("첫 두 후보 비교"); await button("현재 안을 보관본으로 남기기").click(); await visible(page.getByText(/현재 후보·근거·확인 상태를 보관본으로 남겼습니다/));
  const archived = JSON.stringify((await data()).revisions[0]);
  mkdirSync("output/playwright", { recursive: true }); writeFileSync("output/playwright/planning-sample.json", JSON.stringify(await data(), null, 2));
  passed.push("copy-resets-confirmations", "two-options-and-differences", "same-calendar-timeline", "immutable-snapshot-created");
  await button("후보 작성").click(); await page.getByText("장소와 기간별 확인", { exact: true }).click(); await field("행사 종료일").fill("2027-04-12"); await page.getByText("준비 과제 2개", { exact: true }).click(); await visible(page.getByText(/장소·일정·내용이 달라졌습니다/).first());
  await button("이 초안에서 근거 연결 해제").click(); await save(); assert.equal(JSON.stringify((await data()).revisions[0]), archived); assert.equal((await data()).draft.options[0].links.length, 0);
  await button("보관본 1개").click(); await button("보관본 1 · 2027 축제 후보 검증").click(); await page.getByText(/시기 · 2023 논산딸기축제/).first().click(); await visible(page.getByText("52,671.5", { exact: true }).filter({ visible: true }));
  passed.push("date-change-rechecks-preparation", "unlink-keeps-archived-evidence", "archived-real-value-reopened");
  let pending = page.waitForEvent("download"); await button("기획 입력 파일 보관").click(); const exported = readFileSync(await (await pending).path(), "utf8");
  await field("기획 파일을 새 초안으로 가져오기").setInputFiles({ name: "planning.json", mimeType: "application/json", buffer: Buffer.from(exported) }); await visible(page.getByText(/가져오기 전 초안과 기존 보관본/)); const beforeBad = await page.evaluate(k => localStorage.getItem(k), key);
  await field("기획 파일을 새 초안으로 가져오기").setInputFiles({ name: "broken.json", mimeType: "application/json", buffer: Buffer.from("{}") }); await visible(page.getByRole("alert").filter({ hasText: "기획을 읽지 못했습니다" })); assert.equal(await page.evaluate(k => localStorage.getItem(k), key), beforeBad);
  passed.push("file-roundtrip-keeps-both-histories", "corrupt-file-keeps-storage");
  await button("후보 작성").click(); const second = await context.newPage(); watch(second); await second.goto(`${base}/planning/options`); await second.getByLabel("기획 이름", { exact: true }).waitFor();
  await field("기획 이름").fill("첫 창의 미저장 입력"); await second.getByLabel("기획 이름", { exact: true }).fill("두 번째 창의 저장"); await second.getByRole("button", { name: "초안 저장", exact: true }).click(); await second.getByText("이 브라우저에 초안을 저장했습니다.", { exact: true }).waitFor();
  await button("초안 저장").click(); await visible(page.getByRole("alert").filter({ hasText: "다른 창" })); assert.equal(await field("기획 이름").inputValue(), "첫 창의 미저장 입력"); assert.equal((await data()).draft.title, "두 번째 창의 저장");
  pending = page.waitForEvent("download"); await button("입력 보관 후 저장본 다시 열기").click(); await pending; assert.equal(await field("기획 이름").inputValue(), "두 번째 창의 저장"); await second.close();
  await field("기획 이름").fill("이동 전 미저장"); await page.getByRole("link", { name: "관광지도", exact: true }).last().click(); assert.ok(page.url().includes("/planning/options")); await visible(page.getByRole("alert").filter({ hasText: "미저장 입력" })); await save();
  passed.push("two-tab-conflict-preserves-both-inputs", "unsaved-navigation-keeps-input");
  const beforeQuota = await page.evaluate(k => localStorage.getItem(k), key); await page.evaluate(k => { const original = Storage.prototype.setItem; window.__restorePlanningStorage = () => { Storage.prototype.setItem = original; }; Storage.prototype.setItem = function (name, value) { if (name === k) throw new Error("검증용 저장 공간 부족"); return original.call(this, name, value); }; }, key);
  await field("기획 이름").fill("저장 실패에도 유지"); await button("초안 저장").click(); await visible(page.getByRole("alert").filter({ hasText: "저장 공간 부족" })); assert.equal(await page.evaluate(k => localStorage.getItem(k), key), beforeQuota); await page.evaluate(() => window.__restorePlanningStorage()); await save();
  await page.setViewportSize({ width: 390, height: 844 }); await button("같은 항목으로 비교").click(); assert.equal(await page.evaluate(() => document.documentElement.scrollWidth), 390);
  mkdirSync("output/playwright", { recursive: true }); await page.screenshot({ path: "output/playwright/planning-mobile.png", fullPage: true });
  await page.goto(`${base}/regions`); await page.goto(`${base}/planning/options`); assert.equal(await field("기획 담당 지역").inputValue(), "44/150");
  passed.push("quota-failure-keeps-input", "390px-no-page-overflow", "exploration-keeps-owner-region");
  assert.deepEqual(errors, []); assert.deepEqual(writes, []); console.log(JSON.stringify({ headless: true, passed, browserErrors: errors.length, clientWrites: writes.length }));
} finally { await browser.close(); }
