"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { COMPARISON_KEY, encodeComparisons, MAX_BYTES, parseComparisons, storeComparisons } from "@/lib/comparison/evidence";
import type { ComparisonEvidence as Saved } from "@/lib/comparison/types";
import { REGIONS } from "@/lib/region/model";
import type { SearchContext } from "@/lib/comparison/types";
import { Availability, CostCharts, ScheduleChart, SourceDetails, VisitComparison } from "./ComparisonCharts";
import { ComparisonSearchRange } from "./ComparisonSearchRange";
function queryText(q:SearchContext){return `${q.mode==="archive"?"과거 회차":"현재 등록 행사"} · ${q.regions.map(k=>{const r=REGIONS.find(r=>`${r.provinceCode}/${r.districtCode}`===k);return r?`${r.provinceName} ${r.districtName}`:k;}).join(", ")||"전체 지역"} · ${q.start} ~ ${q.end} · ${q.dateRule==="overlap"?"기간 겹침":"기간 안 시작"} · 이름 ${q.keyword||"전체"} · 주제 ${q.theme||"전체"}`;}
export function ComparisonEvidence(){
  const [items,setItems]=useState<Saved[]>([]),[ready,setReady]=useState(false),[message,setMessage]=useState("");
  useEffect(()=>{const read=()=>{try{const raw=localStorage.getItem(COMPARISON_KEY);setItems(raw?parseComparisons(raw):[]);}catch{setMessage("비교 근거를 읽지 못했습니다. 기존 저장값은 유지됩니다.");}setReady(true);};read();window.addEventListener("storage",read);return()=>window.removeEventListener("storage",read);},[]);
  function download(){const url=URL.createObjectURL(new Blob([encodeComparisons(items)],{type:"application/json"})),a=document.createElement("a");a.href=url;a.download=`fest-compass-comparisons-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  async function restore(file?:File){if(!file)return;try{if(file.size>MAX_BYTES)throw new Error("비교 근거 파일은 2MB 이하여야 합니다.");const result=storeComparisons(parseComparisons(await file.text()));setItems(result.items);setMessage(`비교 근거 ${result.added}개를 추가했습니다. 같은 자료는 중복 저장하지 않습니다.`);}catch(e){setMessage(e instanceof Error?e.message:"비교 근거를 저장하지 못했습니다.");}}
  return <section id="comparisons" className="mt-10 scroll-mt-48 space-y-4 border-t border-ink/10 pt-8"><h2 className="text-2xl font-extrabold">담은 축제 비교</h2><p className="text-sm leading-7 text-muted">회차를 선택할 때의 원문·값·검색 조건을 보관한 사본입니다. 현재 자료가 바뀌어도 이 사본은 유지됩니다. 지역 근거와 비교 근거는 각각 파일로 보관합니다.</p><div className="no-print flex flex-wrap gap-2"><Link href="/compare" className="region-primary">축제 비교 더 찾기</Link><button className="region-button" disabled={!items.length} onClick={download}>비교 근거 파일 보관</button><label className="region-button cursor-pointer">비교 근거 파일 가져오기<input type="file" className="sr-only" accept="application/json,.json" onChange={e=>{void restore(e.target.files?.[0]);e.target.value="";}}/></label></div>
    {message&&<p role="status" className="rounded-xl bg-blue-soft p-4 text-sm">{message}</p>}{!ready?<p role="status">비교 근거를 불러오고 있습니다.</p>:<p className="font-bold">보관 비교 {items.length}개 / 최대 50개</p>}
    {items.map(item=><article key={item.id} className="region-card space-y-4"><h3 className="text-lg font-extrabold">{item.title}</h3><Link className="region-primary no-print" href={`/planning/options?evidence=comparison:${item.id}`}>이 비교 근거로 후보 기획 →</Link><p className="text-sm">선택: {item.selection.kind==="visits"?`행사 시작일 기준 ${item.selection.from} ~ ${item.selection.to}일`:item.selection.kind==="cost"?item.editions.find(e=>item.selection.kind==="cost"&&e.id===item.selection.editionId)?.costs.find(c=>item.selection.kind==="cost"&&c.id===item.selection.costId)?.label:"회차와 비교 조건 전체"}</p><p className="text-xs text-muted">담은 시각 {new Date(item.savedAt).toLocaleString("ko-KR",{timeZone:"Asia/Seoul"})} · 조회 {item.context.start} ~ {item.context.end}</p><p className="whitespace-pre-wrap text-sm">참고 이유: {item.note||"메모 없음"}</p>
      <details className="comparison-snapshot"><summary className="cursor-pointer font-bold text-blue">당시 비교 그래프·수치·출처 보기</summary><div className="mt-4 space-y-4"><Availability editions={item.editions}/><ScheduleChart editions={item.editions}/><VisitComparison editions={item.editions} initialRange={item.selection.kind==="visits"?item.selection:undefined}/><CostCharts editions={item.editions}/>{item.editions.map(e=><div key={e.id} className="rounded-xl border border-ink/10 p-4"><h4 className="mb-2 font-bold">{e.year} {e.name}</h4><p className="text-sm leading-7">{e.status} · {e.statusNote}<br/>추가 확인: {e.missing.join(" · ")}</p><ComparisonSearchRange query={e.discoveredWith??item.context} editions={[e]}/><SourceDetails source={e.source}/>{e.statusSource&&<SourceDetails source={e.statusSource}/>}<p className="break-all text-xs leading-6 text-muted">축제 {e.festivalId} · 회차 {e.id}<br/>선택 당시 검색: {queryText(e.discoveredWith??item.context)}</p></div>)}</div></details>
    </article>)}
  </section>;
}
