"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { EVIDENCE_KEY, parseEvidence } from "@/lib/region/evidence";
import { COMPARISON_KEY, parseComparisons } from "@/lib/comparison/evidence";
import { REGIONS } from "@/lib/region/model";
import { archive, connectEvidence, copy, duplicateOption, encodePlanning, importPlanning, MAX_PLANNING_BYTES, newOption, newPlanning, optionIssues, parsePlanning, PLANNING_KEY, pruneEvidence, today, uid, validatePlanning, writePlanning } from "@/lib/planning/model";
import { applyVenueEvidence } from "@/lib/planning/venue-evidence";
import { VenueEvidence } from "./planning/VenueEvidence";
import { FIELDS } from "@/lib/planning/types";
import type { Delivery, Option, Planning, SourceCopy } from "@/lib/planning/types";
import { Field, Select } from "./planning/Fields";
import { EvidenceView } from "./planning/EvidenceView";
import { OptionComparison } from "./planning/OptionComparison";
import { RecordDetails } from "./planning/RecordDetails";
import { Preparation, VenueEditor } from "./planning/Preparation";
import { BudgetWorkspace } from "./planning/budget/Workspace";
import { BudgetReadOnly } from "./planning/budget/ReadOnly";
import { Proposal } from "./planning/Proposal";
import { Outcomes, OutcomeNotes } from "./planning/outcomes/Workspace";
import { renewBudget } from "@/lib/planning/budget-model";

function download(raw: string, name: string) { const url = URL.createObjectURL(new Blob([raw], { type: "application/json" })), a = document.createElement("a"); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
const relationNames = { unknown: "미확인", direct: "직접 수행", foundation: "재단 수행", entrust: "위탁", service: "용역", subsidy: "보조 관계" };
export function PlanningWorkspace({ year, initialEvidence, initialTab = "edit" }: { year: number; initialEvidence: string; initialTab?: "edit" | "budget" | "proposal" | "outcomes" }) {
  const [p, setP] = useState<Planning | null>(null), [sources, setSources] = useState<SourceCopy[]>([]), [message, setMessage] = useState(""), [error, setError] = useState(""), [dirty, setDirty] = useState(false), [saving, setSaving] = useState(false), [blocked, setBlocked] = useState(false);
  const expected = useRef<string | null>(null), dirtyRef = useRef(false), savingRef = useRef(false);
  const [active, setActive] = useState(""), [tab, setTab] = useState(initialTab as string), [sourceKey, setSourceKey] = useState(initialEvidence), [field, setField] = useState<keyof typeof FIELDS>("item"), [reason, setReason] = useState(""), [revisionNote, setRevisionNote] = useState(""), [viewRevision, setViewRevision] = useState("");
  useEffect(() => { dirtyRef.current = dirty; }, [dirty]);
  useEffect(() => {
    function readPlan() { try { const raw = localStorage.getItem(PLANNING_KEY), next = raw ? parsePlanning(raw) : newPlanning(year); expected.current = raw; setP(next); setActive(next.draft.options[0].id); setBlocked(false); } catch (e) { setError(e instanceof Error ? e.message : "기획을 읽지 못했습니다."); setBlocked(true); } }
    function readSources() { const result: SourceCopy[] = []; let failed = false; try { const raw = localStorage.getItem(EVIDENCE_KEY); if (raw) result.push(...parseEvidence(raw).map(value => ({ key: `region:${value.id}`, kind: "region" as const, value }))); } catch { failed = true; } try { const raw = localStorage.getItem(COMPARISON_KEY); if (raw) result.push(...parseComparisons(raw).map(value => ({ key: `comparison:${value.id}`, kind: "comparison" as const, value }))); } catch { failed = true; } setSources(result); if (failed) setMessage("일부 근거 보관함을 읽지 못했습니다. 기획에 이미 연결한 사본은 유지됩니다."); }
    function storage(e: StorageEvent) { if (e.key === PLANNING_KEY || e.key === null) { if (dirtyRef.current || savingRef.current) setError("다른 창에서 기획이 변경됐습니다. 미저장 입력을 보관한 뒤 저장본을 다시 여세요."); else readPlan(); } if ([EVIDENCE_KEY, COMPARISON_KEY, null].includes(e.key)) readSources(); }
    function unload(e: BeforeUnloadEvent) { if (dirtyRef.current) { e.preventDefault(); e.returnValue = ""; } }
    function navigate(e: MouseEvent) { const a = (e.target as Element).closest?.("a"); if (dirtyRef.current && a && !a.download && a.target !== "_blank" && new URL(a.href).pathname !== location.pathname) { e.preventDefault(); setError("미저장 입력이 있습니다. 초안을 저장하거나 입력 파일을 보관한 뒤 이동하세요."); } }
    readPlan(); readSources(); window.addEventListener("storage", storage); window.addEventListener("beforeunload", unload); document.addEventListener("click", navigate, true);
    return () => { window.removeEventListener("storage", storage); window.removeEventListener("beforeunload", unload); document.removeEventListener("click", navigate, true); };
  }, [year]);
  function update(next: Planning, strict = false) { if (saving || blocked) return; try { next = { ...next, version: Math.max(next.version, 2) as Planning["version"] }; if (strict) validatePlanning(next); setP(next); dirtyRef.current = true; setDirty(true); setError(""); setMessage(""); } catch (e) { setError(e instanceof Error ? e.message : "입력값을 확인하세요."); } }
  function changeOption(next: Option, strict = false) { if (next.budget) next = { ...next, budget: { ...next.budget, lines: next.budget.lines.map(l => ({ ...l, taskIds: l.taskIds.filter(id => next.tasks.some(t => t.id === id)) })) } }; if (p) update({ ...p, draft: { ...p.draft, options: p.draft.options.map(o => o.id === next.id ? next : o) } }, strict); }
  async function save(next = p, text = "이 브라우저에 초안을 저장했습니다.") {
    if (!next || blocked || saving) return false; savingRef.current = true; setSaving(true); setError("");
    try {
      const base = expected.current;
      const write = () => writePlanning(next, base);
      const raw = navigator.locks ? await navigator.locks.request(PLANNING_KEY, write) : write();
      expected.current = raw; setP(parsePlanning(raw)); dirtyRef.current = false; setDirty(false); setMessage(text); return true;
    } catch (e) { setError(e instanceof Error ? e.message : "저장하지 못했습니다. 입력은 화면에 유지됩니다."); return false; } finally { savingRef.current = false; setSaving(false); }
  }
  function exportInput() { if (!p) return; download(JSON.stringify(p, null, 2), `fest-compass-planning-${today()}.json`); setMessage("현재 입력을 파일로 보관했습니다. 날짜·참조 오류가 있으면 수정 후 가져올 수 있습니다."); }
  function reload() { if (dirty && p) exportInput(); try { const raw = localStorage.getItem(PLANNING_KEY), next = raw ? parsePlanning(raw) : newPlanning(year); expected.current = raw; setP(next); setActive(next.draft.options[0].id); dirtyRef.current = false; setDirty(false); setBlocked(false); setError(""); setMessage("저장된 기획을 다시 열었습니다."); } catch (e) { setError(e instanceof Error ? e.message : "저장된 기획을 읽지 못했습니다."); } }
  async function restore(file?: File) { if (!file || !p) return; try { if (file.size > MAX_PLANNING_BYTES) throw new Error("기획 파일은 5MB 이하여야 합니다."); const incoming = parsePlanning(await file.text()), next = importPlanning(p, incoming); if (await save(next, "가져오기 전 초안과 기존 보관본을 남기고 파일의 기획을 새 초안으로 열었습니다.")) setActive(next.draft.options[0].id); } catch (e) { setError(e instanceof Error ? e.message : "기획을 가져오지 못했습니다."); } }
  if (!p) return <section className="region-card"><h1 className="text-2xl font-extrabold">올해 기획 후보</h1><p className="mt-4" role={error ? "alert" : "status"}>{error || "이 브라우저의 기획을 불러오고 있습니다."}</p>{blocked && <button className="region-button mt-4" onClick={() => { const raw = localStorage.getItem(PLANNING_KEY); if (raw) download(raw, "fest-compass-planning-recovery.json"); }}>기존 저장값 복구용 파일 보관</button>}</section>;
  const d = p.draft, o = d.options.find(x => x.id === active) ?? d.options[0];
  const choices = [...d.evidence, ...sources.filter(s => !d.evidence.some(e => e.key === s.key))];
  const selectedSource = choices.find(s => s.key === sourceKey), revision = p.revisions.find(r => r.id === viewRevision);
  const changeDraft = (patch: Partial<typeof d>) => update({ ...p, draft: { ...d, ...patch } });
  return <div className={`planning-workspace space-y-6 ${["proposal", "outcomes"].includes(tab) ? "proposal-workspace" : ""}`}><header><p className="text-xs font-extrabold text-blue">공공데이터 근거에서 올해 기획으로</p><h1 className="mt-2 text-3xl font-extrabold">{tab === "outcomes" ? "비용·결과와 다음 회차" : tab === "proposal" ? "기획안 보관·출력" : tab === "budget" ? "예산·준비 규모 비교" : "올해 기획 후보"}</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-muted">아이템·장소·시기가 다른 안을 만들고, 선택한 이유를 자료와 함께 남기세요. 입력은 이 브라우저에만 저장됩니다. 공식 결재·예산 확정은 별도 업무입니다.</p></header>
    <div className="no-print sticky top-28 z-20 flex flex-wrap items-center gap-2 rounded-2xl border border-ink/15 bg-paper/95 p-3 backdrop-blur"><strong className={`mr-2 text-sm ${dirty ? "text-coral" : "text-teal"}`}>{saving ? "저장 중" : dirty || expected.current === null ? "미저장 입력 있음" : "저장된 초안"}</strong><button className="region-primary" disabled={saving || blocked} onClick={() => void save(p, "이 브라우저에 초안을 저장했습니다.")}>초안 저장</button><button className="region-button" onClick={exportInput}>기획 입력 파일 보관</button><button className="region-button" disabled={saving} onClick={reload}>입력 보관 후 저장본 다시 열기</button></div>
    {error && <p role="alert" className="rounded-xl bg-coral-soft p-4 text-sm">{error}</p>}{message && <p role="status" className="rounded-xl bg-blue-soft p-4 text-sm">{message}</p>}
    <div className="no-print flex flex-wrap gap-3"><Link className="region-button" href="/regions">관광지도</Link><Link className="region-button" href="/compare">축제 비교</Link><Link className="region-button" href="/evidence">담은 근거</Link></div>
    <nav className="no-print flex flex-wrap gap-2" aria-label="기획 화면"><button className="region-button" aria-pressed={tab === "edit"} onClick={() => setTab("edit")}>후보 작성</button><button className="region-button" aria-pressed={tab === "compare"} onClick={() => setTab("compare")}>같은 항목으로 비교</button><button className="region-button" aria-pressed={tab === "budget"} onClick={() => setTab("budget")}>예산·준비 규모</button><button className="region-button" aria-pressed={tab === "proposal"} onClick={() => setTab("proposal")}>기획안 보관·출력</button><button className="region-button" aria-pressed={tab === "outcomes"} onClick={() => setTab("outcomes")}>비용·결과·다음 회차</button><button className="region-button" aria-pressed={tab === "history"} onClick={() => setTab("history")}>보관본 {p.revisions.length}개</button></nav>
    <fieldset disabled={saving || blocked} className="min-w-0 space-y-5">
    {d.previousOutcomeId && tab === "edit" && <section className="region-card space-y-3"><h2 className="text-xl font-bold">전회차 개선에서 이어온 기획</h2><p className="text-sm">이전 자료·견적·분류는 재확인 필요입니다. 일정·선택 판단·외부 확인은 새로 기록하세요.</p><details><summary className="cursor-pointer font-bold">원본 결과의 문제·조치·차기 예산 확인</summary><OutcomeNotes draft={p.outcomes!.revisions.find(r => r.id === d.previousOutcomeId)!.draft} /></details></section>}
    {tab === "outcomes" && <Outcomes planning={p} change={update} save={save} edit={() => { setActive(""); setTab("edit"); }} />}
    {tab === "edit" && <><section className="region-card"><h2 className="mb-4 text-xl font-extrabold">기획 담당 지역·사업</h2><div className="grid gap-4 sm:grid-cols-3"><Field label="기획 이름" max={200} value={d.title} onChange={title => changeDraft({ title })} /><Field label="사업연도" type="number" value={String(d.year)} onChange={v => changeDraft({ year: Number(v) })} /><Select label="기획 담당 지역" value={d.regionKey} onChange={regionKey => changeDraft({ regionKey })}><option value="">지역 선택</option>{REGIONS.map(r => <option key={`${r.provinceCode}/${r.districtCode}`} value={`${r.provinceCode}/${r.districtCode}`}>{r.provinceName} {r.districtName}</option>)}</Select></div><p className="mt-3 text-xs text-muted">다른 지역을 탐색하거나 그 지역 자료를 연결해도 이 담당 지역은 바뀌지 않습니다.</p>
      <details className="mt-5"><summary className="cursor-pointer font-bold">사업 정보와 수행 관계</summary><div className="my-4 grid gap-3 sm:grid-cols-2"><Field label="담당 부서" max={200} value={d.department} onChange={department => changeDraft({ department })} /><Select label="신규·계속 여부" value={d.continuity} onChange={v => changeDraft({ continuity: v as typeof d.continuity })} options={{ unknown: "미확인", new: "신규", continuing: "계속" }} /><Field label="사업 시작일" type="date" value={d.period.start} onChange={start => changeDraft({ period: { ...d.period, start } })} /><Field label="사업 종료일" type="date" value={d.period.end} onChange={end => changeDraft({ period: { ...d.period, end } })} /><Field label="작성 기준일" type="date" value={d.asOf} onChange={asOf => changeDraft({ asOf })} /></div><Field label="사업 목적" value={d.purpose} onChange={purpose => changeDraft({ purpose })} multiline /><h3 className="my-4 font-bold">기관별 수행 관계</h3><p className="mb-3 text-xs text-muted">기관 유형으로 위탁·보조 관계를 자동 분류하지 않습니다. 미정 항목도 초안에 남길 수 있습니다.</p>{d.relations.map((r, i) => { const set = (patch: Partial<Delivery>) => changeDraft({ relations: d.relations.map(x => x.id === r.id ? { ...x, ...patch } : x) }); return <fieldset key={r.id} className="mb-3 rounded-xl bg-paper p-4"><legend className="font-bold">수행 관계 {i + 1}</legend><div className="grid gap-3 sm:grid-cols-2"><Field label="수행 조직·역할" max={200} value={r.organization} onChange={organization => set({ organization })} /><Select label="수행 관계" value={r.relation} onChange={relation => set({ relation: relation as Delivery["relation"] })} options={relationNames} /><Field label="업무 범위" value={r.scope} onChange={scope => set({ scope })} /><Field label="관계 확인 참조" value={r.reference} onChange={reference => set({ reference })} /><Field label="관계 확인일" type="date" value={r.checkedAt} onChange={checkedAt => set({ checkedAt })} /></div><button className="region-button mt-3" onClick={() => changeDraft({ relations: d.relations.filter(x => x.id !== r.id) })}>이 수행 관계 제외</button></fieldset>; })}<button className="region-button" disabled={d.relations.length >= 20} onClick={() => changeDraft({ relations: [...d.relations, { id: uid(), organization: "", relation: "unknown", scope: "", reference: "", checkedAt: "" }] })}>수행 관계 추가</button></details></section>
      <section className="space-y-4"><div className="flex flex-wrap items-center gap-2"><h2 className="mr-2 text-xl font-extrabold">기획 후보 {d.options.length}개</h2><button className="region-button" disabled={d.options.length >= 6} onClick={() => { const next = newOption(`후보 ${String.fromCharCode(65 + d.options.length)}`); changeDraft({ options: [...d.options, next] }); setActive(next.id); }}>빈 후보 추가</button><button className="region-button" disabled={d.options.length >= 6} onClick={() => { const next = duplicateOption(o); changeDraft({ options: [...d.options, next] }); setActive(next.id); setMessage("후보를 복사했습니다. 선택 판단·장소 확인·과제 기한과 진행·외부 확인은 새로 기록하세요."); }}>현재 후보 복사</button></div>
      <div className="no-print flex flex-wrap gap-2" role="group" aria-label="편집할 후보">{d.options.map(x => <button className="region-button max-w-full break-words" aria-pressed={o.id === x.id} key={x.id} onClick={() => setActive(x.id)}>{x.name || "이름 미정"}</button>)}</div>
      <div className="region-card"><h3 className="mb-4 text-lg font-extrabold">{o.name || "이름 미정"} 편집</h3><div className="grid gap-3 sm:grid-cols-2"><Field label="후보 이름" max={200} value={o.name} onChange={name => changeOption({ ...o, name })} /><Field label="주제" value={o.theme} onChange={theme => changeOption({ ...o, theme })} /><Field label="아이템·프로그램" value={o.item} onChange={item => changeOption({ ...o, item })} /><Field label="참여 대상" value={o.audience} onChange={audience => changeOption({ ...o, audience })} /><Field label="후보 장소·주소" value={o.venue} onChange={venue => changeOption({ ...o, venue })} /><Select label="후보 판단" value={o.decision} onChange={v => { const decision = v as Option["decision"]; changeDraft({ options: d.options.map(x => x.id === o.id ? { ...o, decision } : decision === "selected" && x.decision === "selected" ? { ...x, decision: "undecided" } : x) }); }} options={{ undecided: "검토 중", selected: "우선 후보", excluded: "제외 후보" }} /></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="담당자 가정" multiline value={o.assumptions} onChange={assumptions => changeOption({ ...o, assumptions })} /><Field label="제약·미확인 사항" multiline value={o.constraints} onChange={constraints => changeOption({ ...o, constraints })} /></div><div className="mt-3"><Field label="선택·제외 이유" multiline value={o.reason} onChange={reason => changeOption({ ...o, reason })} /></div><p className="mt-4 text-sm text-muted">확인 필요: {optionIssues(o).join(" · ") || "기본 항목 입력됨 · 장소·준비 상세 확인 필요"}</p></div>
      <section className="region-card space-y-4"><h3 className="text-lg font-extrabold">{o.name}에 판단 근거 연결</h3><p className="text-sm text-muted">선택 당시 수치·조회 조건·출처를 이 기획 안에도 사본으로 남깁니다. 아래 판단 이유는 담당자의 해석입니다.</p><div className="grid gap-3 sm:grid-cols-2"><Select label="연결할 보관 근거" value={sourceKey} onChange={setSourceKey}><option value="">근거 선택</option>{choices.map(s => <option key={s.key} value={s.key}>{s.kind === "region" ? "지역" : "비교"} · {s.value.title}</option>)}</Select><Select label="근거를 적용할 판단" value={field} onChange={v => setField(v as keyof typeof FIELDS)} options={FIELDS} /></div><Field label="이 자료를 참고하는 판단 이유" multiline value={reason} onChange={setReason} />{selectedSource && <VenueEvidence source={selectedSource} current={o.venue} apply={() => { try { update({ ...p, draft: applyVenueEvidence(d, o.id, selectedSource, reason) }, true); } catch (e) { setError(e instanceof Error ? e.message : "장소를 입력하지 못했습니다."); } }} />}{selectedSource && <details><summary className="cursor-pointer font-bold text-blue">연결 전 당시 값·출처 확인</summary><div className="mt-3"><EvidenceView source={selectedSource} /></div></details>}<button className="region-primary" disabled={!selectedSource} onClick={() => { if (selectedSource) try { update({ ...p, draft: connectEvidence(d, o.id, selectedSource, field, reason) }, true); } catch (e) { setError(e instanceof Error ? e.message : "근거를 연결하지 못했습니다."); } }}>선택한 근거 연결</button>{!choices.length && <p className="text-sm text-muted">담은 근거가 없습니다. 초안 저장 후 관광지도나 축제 비교에서 자료를 담아 오세요. 자료가 없을 때는 담당자 가정을 적을 수 있습니다.</p>}
      {o.links.map(l => { const s = d.evidence.find(e => e.key === l.sourceKey)!; return <article key={`${l.sourceKey}/${l.field}`} className="rounded-xl border border-ink/15 p-4"><p className="font-bold">{FIELDS[l.field]} · {s.value.title}</p><p className="my-2 whitespace-pre-wrap text-sm">담당자 판단: {l.reason || "이유 미입력"}</p><details><summary className="cursor-pointer text-sm font-bold text-blue">기획에 연결한 당시 자료 보기</summary><div className="mt-4"><EvidenceView source={s} /></div></details><button className="region-button mt-3" onClick={() => { const next = copy(p); next.draft.options.find(x => x.id === o.id)!.links = o.links.filter(x => x !== l); pruneEvidence(next.draft); update(next); }}>이 초안에서 근거 연결 해제</button></article>; })}</section>
      <VenueEditor key={`venue-${o.id}`} option={o} change={changeOption} /><Preparation key={`tasks-${o.id}`} option={o} change={changeOption} />
      <p className="text-sm leading-7 text-muted">예산·준비 규모 탭에서 이 후보의 수량·기간·단가와 준비 과제를 연결하고 같은 기획 버전으로 보관할 수 있습니다.</p></section></>}
    {tab === "budget" && <BudgetWorkspace planning={p} option={o} select={setActive} change={changeOption} archive={note => { try { void save(archive(p, note), "예산·근거·준비 상태를 보관본으로 남겼습니다."); } catch (e) { setError((e as Error).message); } }} renew={() => { try { const next = archive(p, "예산을 현재 기획 조건으로 재검토하기 전 기록"); next.draft.options.find(x => x.id === o.id)!.budget = renewBudget(o.budget!, d, o); void save(next, "이전 예산을 보관하고 현재 조건의 재검토 초안을 열었습니다."); } catch (e) { setError((e as Error).message); } }} />}
    {tab === "compare" && <><OptionComparison draft={d} /><RecordDetails draft={d} /><div className="no-print region-card space-y-3"><Field label="보관 메모" value={revisionNote} onChange={setRevisionNote} /><button className="region-primary" onClick={() => { try { void save(archive(p, revisionNote), "현재 후보·근거·확인 상태를 보관본으로 남겼습니다. 이후 수정은 초안에만 반영됩니다."); } catch (e) { setError(e instanceof Error ? e.message : "보관하지 못했습니다."); } }}>현재 안을 보관본으로 남기기</button><p className="text-xs text-muted">미정 항목도 그대로 보관합니다. 완성 기획안·공식 승인 문서가 아닙니다.</p></div></>}
    {tab === "proposal" && <Proposal planning={p} change={update} save={save} edit={() => { setActive(p.draft.options[0].id); setTab("edit"); }} />}
    {tab === "history" && <section className="space-y-4"><h2 className="text-2xl font-extrabold">선택 당시 기획 보관본</h2><p className="text-sm leading-7 text-muted">보관본은 후보·자료·당시 확인 상태의 사본입니다. 초안을 고치거나 근거 연결을 해제해도 바뀌지 않습니다. 최대 20개·기획 파일 5MB까지 보관합니다.</p><label className="no-print region-button cursor-pointer">기획 파일을 새 초안으로 가져오기<input type="file" className="sr-only" accept="application/json,.json" onChange={e => { void restore(e.target.files?.[0]); e.target.value = ""; }} /></label><p className="text-xs text-muted">가져오기 직전 초안과 양쪽 보관본을 모두 남깁니다. 기존 지역·비교 근거 파일은 변경하지 않습니다.</p>{!p.revisions.length && <p className="region-card">아직 보관본이 없습니다. 후보 비교 화면에서 현재 안을 보관하세요.</p>}<div className="flex flex-wrap gap-2">{p.revisions.map((r, i) => <button className="region-button" aria-pressed={r.id === viewRevision} key={r.id} onClick={() => setViewRevision(r.id)}>보관본 {i + 1} · {r.draft.title}</button>)}</div>{revision && <div className="region-card space-y-5"><h3 className="text-xl font-extrabold">보관 당시 기획</h3><p className="text-sm">{revision.savedAt} · {revision.note || "메모 없음"}<br />사업 목적: {revision.draft.purpose || "미정"} · 담당 부서: {revision.draft.department || "미정"}</p><OptionComparison draft={revision.draft} /><RecordDetails draft={revision.draft} />{revision.draft.options.map(option => <details key={option.id}><summary className="cursor-pointer font-bold text-blue">{option.name}의 예산·준비 기록 보기</summary><div className="mt-4"><BudgetReadOnly draft={revision.draft} option={option} /></div></details>)}{revision.draft.options.map(option => <section key={option.id} className="space-y-3"><h4 className="text-lg font-bold">{option.name}의 당시 근거</h4>{option.links.map(l => <details key={`${l.sourceKey}/${l.field}`}><summary className="cursor-pointer font-bold text-blue">{FIELDS[l.field]} · {revision.draft.evidence.find(s => s.key === l.sourceKey)!.value.title}</summary><p className="my-3 text-sm">당시 판단 이유: {l.reason || "미입력"}</p><EvidenceView source={revision.draft.evidence.find(s => s.key === l.sourceKey)!} /></details>)}</section>)}<button className="no-print region-button" onClick={() => { try { const next = archive(p, "이전 보관본을 초안으로 열기 전 기록"); next.draft = copy(revision.draft); void save(next, "이전 보관본을 새 초안으로 열었습니다. 기존 보관본과 직전 초안은 유지됩니다.").then(ok => { if (ok) { setActive(next.draft.options[0].id); setTab("edit"); } }); } catch (e) { setError(e instanceof Error ? e.message : "보관본을 열지 못했습니다."); } }}>이 보관본을 새 초안으로 열기</button></div>}</section>}
    </fieldset>
  </div>;
}
