import { compareFund, compareMetric, fundTotal } from "@/lib/planning/outcome-model";
import { RESULT_ORIGINS, RESULT_STAGES } from "@/lib/planning/outcome-types";
import type { OutcomeDraft, ResultValue } from "@/lib/planning/outcome-types";
import type { Revision } from "@/lib/planning/types";
import { VAT } from "@/lib/planning/budget-types";
import { Composition } from "../budget/Charts";
const num = (v: number | null) => v === null ? "미확인" : v.toLocaleString("ko-KR", { maximumFractionDigits: 6 });
export function ResultSource({ value: v }: { value: ResultValue }) { return <p className="break-words text-xs leading-6">{RESULT_ORIGINS[v.origin]} · {v.reference || "참조 미입력"}{v.value === "" && ` · 미확인 사유: ${v.missingReason || "미입력"}`}</p>; }
export function PairChart({ title, planned, actual, comparable, reason, unit }: { title: string; planned: number | null; actual: number | null; comparable: boolean; reason: string; unit: string }) {
  const max = Math.max(1, planned ?? 0, actual ?? 0);
  return <section className="space-y-3"><h4 className="font-bold">{title}</h4>{comparable ? <svg role="img" aria-label={`${title} 계획·결과 막대`} viewBox="0 0 640 125" className="w-full"><title>0에서 시작하는 같은 축 · {unit}</title>{[{ label: "계획", value: planned!, color: "#2667e8" }, { label: "결과", value: actual!, color: "#146b61" }].map((v, i) => <g key={v.label}><text x="0" y={18 + i * 60} fontSize="15">{v.label} {num(v.value)} {unit}</text><rect x="0" y={26 + i * 60} width={v.value / max * 630} height="20" fill={v.color} /><line x1="0" x2="630" y1={48 + i * 60} y2={48 + i * 60} stroke="#c6cfdb" /></g>)}</svg> : <p className="rounded-xl bg-paper p-3 text-sm">그래프·차이 비교 보류 · {reason}</p>}
    <div className="overflow-x-auto"><table className="comparison-table"><caption className="sr-only">{title} 수치 표</caption><thead><tr><th>계획</th><th>결과</th><th>차이</th><th>증감률</th></tr></thead><tbody><tr><td>{num(planned)} {unit}</td><td>{num(actual)} {unit}</td><td>{comparable ? num(actual! - planned!) : "보류"}</td><td>{comparable && planned !== 0 ? `${num((actual! - planned!) / planned! * 100)}%` : "미산정"}</td></tr></tbody></table></div>{reason && <p className="text-xs text-muted">{reason}</p>}
  </section>;
}
export function OutcomeCharts({ draft: d, proposal: p }: { draft: OutcomeDraft; proposal: Revision }) {
  const total = fundTotal(d, p);
  return <div className="space-y-5"><section className="region-card space-y-5"><h3 className="text-xl font-extrabold">계획과 실측 비교</h3><p className="text-sm text-muted">계획값은 아래 참조에서 담당자가 옮겨 적은 값입니다. 기획안 보관 당시 수치가 자동 확정된 것은 아닙니다. 지표 정의·단위·비교 대상 기간을 함께 확인하세요.</p>{!d.metrics.length && <p>등록한 지표 없음 · 성과 미확인</p>}{d.metrics.map(m => { const c = compareMetric(m); return <article key={m.id} className="space-y-3 border-t border-ink/15 pt-4"><PairChart title={m.name || "지표 이름 미정"} {...c} comparable={c.difference !== null} unit={m.planUnit === m.actualUnit ? m.planUnit : "단위 불일치"} /><p className="text-xs leading-6">계획 정의: {m.planDefinition || "미정"} ({m.planUnit || "단위 미정"}) · 결과 정의: {m.actualDefinition || "미정"} ({m.actualUnit || "단위 미정"})<br />비교 대상 기간: {m.period.start || "미정"} ~ {m.period.end || "미정"}<br />계획 근거: {m.planReference || "미입력"}</p><ResultSource value={m.actual} /></article>; })}</section>
    <section className="region-card space-y-5"><h3 className="text-xl font-extrabold">재원별 계획과 실제 사용액</h3><p className="text-sm text-muted">잔액·반납액·이자는 별도 자료 값입니다. 계획과 사용액의 차이로 채우거나 정산 완료를 판정하지 않습니다.</p>{!d.funds.length && <p>기준 기획안에 포함된 재원이 없습니다. 예산·재원을 작성한 기획안을 새 버전으로 보관하세요.</p>}{d.funds.map(f => { const c = compareFund(f, p); return <article key={f.id} className="space-y-3 border-t border-ink/15 pt-4"><PairChart title={c.name} {...c} comparable={c.difference !== null} unit="원" /><p className="text-xs">{RESULT_STAGES[f.stage]} · {VAT[f.vat]} · 실제 사용 범위: {f.scope || "미확인"} · 계획과 범위 일치: {f.scopeMatches ? "담당자 확인" : "미확인"}</p><ResultSource value={f.actual} /><dl className="grid gap-3 sm:grid-cols-3">{([['balance', '잔액'], ['returned', '반납액'], ['interest', '이자']] as const).map(([k, label]) => <div key={k} className="rounded-xl bg-paper p-3"><dt className="font-bold">{label}</dt><dd className="mt-2 text-sm">{f[k].value === "" ? "미확인" : `${Number(f[k].value).toLocaleString("ko-KR")}원`}<ResultSource value={f[k]} /></dd></div>)}</dl></article>; })}
      {total ? <PairChart title="동일 범위 재원 합계" {...total} comparable reason={total.planned === 0 ? "계획 0 · 비율 미산정" : ""} unit="원" /> : <p className="rounded-xl bg-paper p-3 text-sm">합계 비교 보류 · 전체 재원·중복·사업 범위·세금·금액 단계와 미확인 값을 확인하세요.</p>}
    </section>
    <Composition title="실제 사용액의 재원 구성" values={total ? d.funds.map(f => ({ label: compareFund(f, p).name, amount: Number(f.actual.value) })) : []} allowed={!!total && total.actual > 0} reason="같은 단계·범위의 재원 전체와 합계가 확인되어야 합니다. 0원은 구성비를 계산하지 않습니다." />
  </div>;
}
