import { Field, Select } from "../Fields";
import { VAT } from "@/lib/planning/budget-types";
import { EVIDENCE_KINDS, RESULT_ORIGINS, RESULT_STAGES } from "@/lib/planning/outcome-types";
import type { OutcomeDraft, ResultValue } from "@/lib/planning/outcome-types";
import type { Revision } from "@/lib/planning/types";
import { newMetric } from "@/lib/planning/outcome-model";
import { uid } from "@/lib/planning/model";
function ValueEditor({ label, value: v, change }: { label: string; value: ResultValue; change: (v: ResultValue) => void }) {
  return <fieldset className="space-y-3 rounded-xl border border-ink/15 p-3"><legend className="px-2 font-bold">{label}</legend><div className="grid gap-3 sm:grid-cols-2"><Field label={`${label} 값`} value={v.value} onChange={value => change({ ...v, value })} /><Select label={`${label} 출처 구분`} value={v.origin} onChange={origin => change({ ...v, origin: origin as ResultValue['origin'] })} options={RESULT_ORIGINS} /><Field label={`${label} 출처·문서·쪽 참조`} value={v.reference} onChange={reference => change({ ...v, reference })} /><Field label={`${label} 미확인 사유`} value={v.missingReason} onChange={missingReason => change({ ...v, missingReason })} /></div><p className="text-xs text-muted">빈칸은 미확인입니다. 실제 확인한 0만 0으로 입력하세요. 공개 자료 전사값도 담당자가 입력한 기록으로 구분됩니다.</p></fieldset>;
}
export function OutcomeEditor({ draft: d, proposal: p, change }: { draft: OutcomeDraft; proposal: Revision; change: (d: OutcomeDraft) => void }) {
  const option = p.draft.options.find(o => o.decision === "selected")!;
  return <div className="no-print space-y-4"><div className="region-card space-y-3"><h3 className="text-xl font-extrabold">내 행사 결과 입력</h3><Field label="결과 작성 기준일" type="date" value={d.asOf} onChange={asOf => change({ ...d, asOf })} /><Field label="현장 조치·운영 기록" multiline value={d.operations} onChange={operations => change({ ...d, operations })} /><p className="text-sm text-muted">기준 기획안의 측정 계획: {p.draft.measurementPlan || "미정"}</p></div>
    <section className="region-card space-y-4"><h3 className="text-xl font-extrabold">성과 지표와 비교 기준</h3>{d.metrics.map((m, i) => { const set = (patch: Partial<typeof m>) => change({ ...d, metrics: d.metrics.map(v => v.id === m.id ? { ...v, ...patch } : v) }); return <details key={m.id} className="rounded-xl border border-ink/15 p-4"><summary className="cursor-pointer font-bold">지표 {i + 1} · {m.name || "이름 미정"}</summary><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="성과 지표 이름" value={m.name} onChange={name => set({ name })} /><Field label="계획값" value={m.planned} onChange={planned => set({ planned })} /><Field label="계획값 근거·기획안 참조" value={m.planReference} onChange={planReference => set({ planReference })} /><Field label="계획 지표 정의" value={m.planDefinition} onChange={planDefinition => set({ planDefinition })} /><Field label="실측 지표 정의" value={m.actualDefinition} onChange={actualDefinition => set({ actualDefinition })} /><Field label="계획 단위" value={m.planUnit} onChange={planUnit => set({ planUnit })} /><Field label="실측 단위" value={m.actualUnit} onChange={actualUnit => set({ actualUnit })} /><Field label="비교 대상 시작일" type="date" value={m.period.start} onChange={start => set({ period: { ...m.period, start } })} /><Field label="비교 대상 종료일" type="date" value={m.period.end} onChange={end => set({ period: { ...m.period, end } })} /></div><div className="mt-4"><ValueEditor label="실측" value={m.actual} change={actual => set({ actual })} /></div><button className="region-button mt-3" onClick={() => change({ ...d, metrics: d.metrics.filter(v => v.id !== m.id) })}>이 지표 제외</button></details>; })}<button className="region-button" disabled={d.metrics.length >= 30} onClick={() => change({ ...d, metrics: [...d.metrics, newMetric()] })}>성과 지표 추가</button></section>
    <section className="region-card space-y-4"><h3 className="text-xl font-extrabold">재원별 실제 비용·출처</h3><p className="text-sm text-muted">기준 기획안의 포함 재원을 사용합니다. 계획액을 실제 사용액으로 복제하지 않습니다. 입찰·계약·교부액만 확보했다면 실제 사용액은 미확인으로 남기세요.</p>{d.funds.map(f => { const set = (patch: Partial<typeof f>) => change({ ...d, funds: d.funds.map(v => v.id === f.id ? { ...v, ...patch } : v) }); return <details key={f.id} className="rounded-xl border border-ink/15 p-4"><summary className="cursor-pointer font-bold">재원 · {option.budget!.funds.find(v => v.id === f.fundId)!.name || "이름 미정"}</summary><div className="mt-4 grid gap-3 sm:grid-cols-2"><Select label="실제 사용액 단계" value={f.stage} onChange={stage => set({ stage: stage as typeof f.stage })} options={RESULT_STAGES} /><Select label="실제 사용액 세금 기준" value={f.vat} onChange={vat => set({ vat: vat as typeof f.vat })} options={VAT} /><Field label="실제 사용 사업·포함 범위" value={f.scope} onChange={scope => set({ scope })} /></div><label className="my-4 flex items-start gap-2 text-sm"><input type="checkbox" checked={f.scopeMatches} onChange={e => set({ scopeMatches: e.target.checked })} />기준 기획안과 같은 재원·사업·기간·포함 범위임을 확인했습니다.</label><div className="space-y-3">{([['actual', '실제 사용액(원)'], ['balance', '잔액(원)'], ['returned', '반납액(원)'], ['interest', '이자(원)']] as const).map(([key, label]) => <ValueEditor key={key} label={label} value={f[key]} change={value => set({ [key]: value })} />)}</div></details>; })}{!d.funds.length && <p className="text-sm">기획안에 포함된 재원 없음 · 예산·재원 작성 후 기획안을 새 버전으로 보관하세요.</p>}</section>
    <section className="region-card space-y-4"><h3 className="text-xl font-extrabold">증빙과 확인 상태</h3><p className="text-sm text-muted">참조가 있다는 사실과 지출 적정성·공식 정산 완료는 별개입니다. 이곳에는 담당자가 확인한 기록만 남깁니다.</p>{d.evidence.map((e, i) => { const set = (patch: Partial<typeof e>) => change({ ...d, evidence: d.evidence.map(v => v.id === e.id ? { ...v, ...patch } : v) }); return <details key={e.id} className="rounded-xl border border-ink/15 p-4"><summary className="cursor-pointer font-bold">증빙 {i + 1} · {e.scope || "범위 미정"}</summary><div className="mt-4 grid gap-3 sm:grid-cols-2"><Select label="증빙 종류" value={e.kind} onChange={kind => set({ kind: kind as typeof e.kind })} options={EVIDENCE_KINDS} /><Field label="증빙 적용 범위·항목" value={e.scope} onChange={scope => set({ scope })} /><Field label="증빙 참조" value={e.reference} onChange={reference => set({ reference })} /><Select label="증빙 확인 상태" value={e.status} onChange={status => set({ status: status as typeof e.status })} options={{ unknown: "미확인", reviewing: "검토 중", confirmed: "담당자 확인 기록 있음" }} /><Field label="증빙 검토 담당 조직·역할" value={e.reviewer} onChange={reviewer => set({ reviewer })} /><Field label="증빙 확인일" type="date" value={e.checkedAt} onChange={checkedAt => set({ checkedAt })} /><Field label="증빙 보완 사항" value={e.note} onChange={note => set({ note })} /></div></details>; })}<button className="region-button" disabled={d.evidence.length >= 30} onClick={() => change({ ...d, evidence: [...d.evidence, { id: uid(), kind: "unknown", scope: "", reference: "", status: "unknown", reviewer: "", checkedAt: "", note: "" }] })}>증빙 확인 기록 추가</button></section>
    <section className="region-card space-y-4"><h3 className="text-xl font-extrabold">개선과 다음 회차 준비</h3>{d.improvements.map((i, index) => { const set = (patch: Partial<typeof i>) => change({ ...d, improvements: d.improvements.map(v => v.id === i.id ? { ...v, ...patch } : v) }); return <details key={i.id} className="rounded-xl border border-ink/15 p-4"><summary className="cursor-pointer font-bold">개선 {index + 1} · {i.problem || "문제 미입력"}</summary><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="발견한 문제" value={i.problem} onChange={problem => set({ problem })} /><Field label="개선 조치" value={i.action} onChange={action => set({ action })} /><Field label="차기 준비 과제" value={i.nextTask} onChange={nextTask => set({ nextTask })} /><Field label="차기 예산 검토 항목" value={i.nextBudget} onChange={nextBudget => set({ nextBudget })} /><Field label="개선 근거 참조" value={i.reference} onChange={reference => set({ reference })} /></div></details>; })}<button className="region-button" disabled={d.improvements.length >= 20} onClick={() => change({ ...d, improvements: [...d.improvements, { id: uid(), problem: "", action: "", nextTask: "", nextBudget: "", reference: "" }] })}>개선 기록 추가</button></section>
  </div>;
}
