"use client";
import { useRef, useState } from "react";
import Link from "next/link";
import catalogue from "@/data/festival-editions.json";
import type { Edition } from "@/lib/comparison/types";
import { CostCharts } from "@/components/ComparisonCharts";
import { REGIONS } from "@/lib/region/model";
import { archiveOutcome, nextEdition, startOutcome } from "@/lib/planning/outcome-model";
import { copy } from "@/lib/planning/model";
import { EVIDENCE_KINDS } from "@/lib/planning/outcome-types";
import type { OutcomeDraft, OutcomeRevision } from "@/lib/planning/outcome-types";
import type { Planning } from "@/lib/planning/types";
import { Field, Select } from "../Fields";
import { ProposalReport, usePrintDetails } from "../Proposal";
import { OutcomeCharts } from "./Charts";
import { OutcomeEditor } from "./Editor";

export function OutcomeNotes({ draft: d }: { draft: OutcomeDraft }) {
  return <><section className="region-card space-y-3"><h3 className="text-xl font-extrabold">현장 조치·운영 기록</h3><p className="whitespace-pre-wrap text-sm leading-7">{d.operations || "기록 없음 · 미확인"}</p></section><section className="region-card space-y-4"><h3 className="text-xl font-extrabold">증빙 확인 기록</h3><p className="text-sm text-muted">참조 존재만으로 지출 적정성·공식 정산 완료를 판정하지 않습니다.</p>{!d.evidence.length && <p className="text-sm">증빙 확인 기록 없음</p>}{d.evidence.map(e => <article key={e.id} className="border-t border-ink/15 pt-3 text-sm leading-7"><strong>{EVIDENCE_KINDS[e.kind]} · {e.scope || "범위 미정"}</strong><p>상태: {e.status === "confirmed" ? "담당자 확인 기록 있음" : e.status === "reviewing" ? "검토 중" : "미확인"}<br />참조: {e.reference || "미입력"}<br />검토: {e.reviewer || "미정"} · {e.checkedAt || "확인일 미정"}<br />보완 사항: {e.note || "기록 없음"}</p></article>)}</section><section className="region-card space-y-4"><h3 className="text-xl font-extrabold">개선과 차기 예산·준비</h3>{!d.improvements.length && <p className="text-sm">등록한 개선 기록 없음</p>}{d.improvements.map((i, index) => <article key={i.id} className="border-t border-ink/15 pt-3 text-sm leading-7"><h4 className="font-bold">{index + 1}. {i.problem || "문제 미입력"}</h4><p className="whitespace-pre-wrap">조치: {i.action || "미정"}<br />차기 준비 과제: {i.nextTask || "미정"}<br />차기 예산 검토: {i.nextBudget || "미정"}<br />근거: {i.reference || "미입력"}</p></article>)}</section></>;
}
function OutcomeReport({ planning: p, revision: r }: { planning: Planning; revision: OutcomeRevision }) {
  const ref = useRef<HTMLDivElement>(null); usePrintDetails(ref);
  const proposal = p.revisions.find(v => v.id === r.draft.proposalId)!, pnumber = p.revisions.filter(v => v.proposal).indexOf(proposal) + 1, rnumber = p.outcomes!.revisions.indexOf(r) + 1;
  return <div ref={ref} className="outcome-report report-sheet space-y-5" data-outcome-id={r.id}><header className="region-card space-y-3"><h2 className="text-2xl font-extrabold">{proposal.draft.title} · 결과·개선 자료</h2><p className="text-sm leading-7">개인 보관본 · 기획 P{pnumber} / 결과 R{rnumber}<br />{proposal.draft.year}년 · 결과 기준일 {r.draft.asOf || "미정"}<br />기획 보관 {proposal.savedAt} · 결과 보관 {r.savedAt}<br />메모: {r.note || "없음"}</p><p className="break-all text-xs leading-6">기획 식별자 {proposal.id}<br />결과 식별자 {r.id} · 출력 형식 1</p><p className="text-sm text-muted">고정한 기획·결과 사본입니다. 개인 기록이며 공식 정산·결재 문서가 아닙니다.</p></header><OutcomeCharts draft={r.draft} proposal={proposal} /><OutcomeNotes draft={r.draft} /><details className="region-card"><summary className="cursor-pointer font-bold">기준 기획안·예산·당시 공공데이터 근거</summary><div className="mt-4"><ProposalReport revision={proposal} number={pnumber} kind="business" generatedAt={r.savedAt} /></div></details></div>;
}
export function Outcomes({ planning: p, change, save, edit }: { planning: Planning; change: (p: Planning) => void; save: (p: Planning, message: string) => Promise<boolean>; edit: () => void }) {
  const [mode, setMode] = useState("public"), [query, setQuery] = useState(""), [region, setRegion] = useState(""), [year, setYear] = useState(""), [proposalId, setProposalId] = useState(""), [selected, setSelected] = useState(""), [note, setNote] = useState(""), [nextYear, setNextYear] = useState(""), [error, setError] = useState("");
  const proposals = p.revisions.filter(r => r.proposal), d = p.outcomes?.draft, proposal = proposals.find(r => r.id === d?.proposalId), revisions = p.outcomes?.revisions ?? [];
  const matches = (title: string, key: string, y: number) => title.toLowerCase().includes(query.trim().toLowerCase()) && (!region || key === region) && (!year || String(y) === year);
  const publicEditions = (catalogue.editions as Edition[]).filter(e => matches(e.name, `${e.region.province}/${e.region.district}`, e.year));
  const histories = revisions.filter(r => { const p0 = proposals.find(v => v.id === r.draft.proposalId)!; return matches(p0.draft.title, p0.draft.regionKey, p0.draft.year); });
  const result = histories.find(r => r.id === selected) ?? histories.at(-1);
  async function perform(fn: () => Planning, message: string, after?: (n: Planning) => void) { try { setError(""); const n = fn(); if (await save(n, message)) after?.(n); } catch (e) { setError((e as Error).message); } }
  return <section className="space-y-5"><div className="no-print region-card space-y-4"><h2 className="text-2xl font-extrabold">공개 비용 자료에서 다음 회차까지</h2><p className="text-sm leading-7">공개 사례를 조회하고 내 행사의 결과를 따로 기록합니다. 공개 비용은 확보한 원문 표본이며 전국 모든 축제의 집행액을 조회하는 서비스는 아직 아닙니다.</p><div className="flex flex-wrap gap-2" role="group" aria-label="결과 화면 선택">{Object.entries({ public: "공개 비용 사례", edit: "내 행사 결과 입력", history: "개인 과거 회차·출력" }).map(([key, name]) => <button key={key} className="region-button" aria-pressed={mode === key} onClick={() => setMode(key)}>{name}</button>)}</div></div>
    {error && <p role="alert" className="no-print region-card text-coral">{error}</p>}
    {mode !== "edit" && <div className="no-print region-card grid gap-3 sm:grid-cols-3"><Field label="공개 사례·개인 회차 검색어" value={query} onChange={setQuery} max={200} /><Select label="결과 조회 지역" value={region} onChange={setRegion}><option value="">전국</option>{REGIONS.map(r => <option key={`${r.provinceCode}/${r.districtCode}`} value={`${r.provinceCode}/${r.districtCode}`}>{r.provinceName} {r.districtName}</option>)}</Select><Field label="결과 조회 사업연도" value={year} onChange={setYear} max={4} /></div>}
    {mode === "public" && <div className="space-y-5"><h3 className="text-xl font-extrabold">공개 원문 사례 {publicEditions.length}회차 · 비용 확보 {publicEditions.filter(e => e.costs.length).length}회차</h3><p className="text-sm text-muted">공개 자료를 확인해 구조화한 조회값입니다. 담당자가 입력한 내 행사 결과와 합산하지 않습니다. 같은 검색 조건의 개인 결과는 {histories.length}개입니다.</p>{publicEditions.length ? publicEditions.map(e => <section key={e.id} className="space-y-3"><h4 className="font-bold">{e.year} {e.name} · {e.region.name}</h4>{e.costs.length ? <CostCharts editions={[e]} /> : <p className="region-card text-sm">실제 비용 자료 미확보 · 0원으로 표시하지 않습니다.</p>}</section>) : <p className="region-card">이 조건의 공개 표본이 없습니다.</p>}<Link className="region-button inline-block" href="/compare">축제 일정·방문 추세와 함께 비교</Link></div>}
    {mode === "edit" && <><div className="no-print region-card space-y-4"><h3 className="text-xl font-extrabold">결과의 기준 기획안</h3><Select label="결과를 기록할 기획안" value={proposalId || proposals.at(-1)?.id || ""} onChange={setProposalId}><option value="">기획안 선택</option>{proposals.map((r, i) => <option key={r.id} value={r.id}>P{i + 1} · {r.draft.year} {r.draft.title}</option>)}</Select><button className="region-primary" disabled={!proposals.length} onClick={() => void perform(() => startOutcome(p, proposalId || proposals.at(-1)!.id), "기준 기획안의 결과 초안을 열었습니다. 기존 결과 초안은 보관했습니다.")}>이 기획안으로 결과 초안 시작</button>{!proposals.length && <p className="text-sm">기획안 보관·출력 탭에서 먼저 기획안을 보관하세요.</p>}<p className="text-xs text-muted">다른 결과를 열면 현재 결과 초안을 보관합니다. 기획안 자체는 변경하지 않습니다.</p></div>{d && proposal && <><p className="region-card text-sm">현재 결과 기준: P{proposals.indexOf(proposal) + 1} · {proposal.draft.year} {proposal.draft.title}</p><OutcomeEditor draft={d} proposal={proposal} change={draft => change({ ...p, version: 4, outcomes: { ...p.outcomes!, draft } })} /><OutcomeCharts draft={d} proposal={proposal} /><div className="no-print region-card space-y-3"><Field label="결과 버전 보관 메모" value={note} onChange={setNote} /><button className="region-primary" onClick={() => void perform(() => archiveOutcome(p, note), "결과를 새 버전으로 보관했습니다. 기존 결과 출력은 유지됩니다.", n => { setSelected(n.outcomes!.revisions.at(-1)!.id); setMode("history"); setQuery(""); setRegion(""); setYear(""); })}>현재 결과를 새 버전으로 보관</button><p className="text-xs text-muted">결과 보관본 최대 20개 · 기획과 합쳐 파일 5MB. 미확인 항목도 그대로 보관합니다.</p></div></>}</>}
    {mode === "history" && <><p className="no-print region-card text-sm">개인 과거 회차 결과 {histories.length}개 · 같은 조건의 공개 표본 {publicEditions.length}회차. 이 브라우저의 기획 파일에 보관한 기록만 검색합니다.</p>{!result ? <p className="region-card">조건에 맞는 개인 결과 보관본이 없습니다. 내 행사 결과 입력에서 결과를 기록·보관하세요.</p> : <><div className="no-print region-card space-y-4"><Select label="출력할 결과 버전" value={result.id} onChange={setSelected}>{histories.map(r => { const p0 = proposals.find(v => v.id === r.draft.proposalId)!; return <option key={r.id} value={r.id}>R{revisions.indexOf(r) + 1} · {p0.draft.year} {p0.draft.title} · {r.savedAt}</option>; })}</Select><div className="flex flex-wrap gap-2"><button className="region-primary" onClick={() => window.print()}>결과·개선 자료 인쇄·PDF 저장</button><button className="region-button" onClick={() => void perform(() => { const n = p.outcomes?.draft ? archiveOutcome(p, "결과 보관본을 수정하기 직전 초안") : copy(p); n.outcomes!.draft = copy(result.draft); return n; }, "이전 결과를 수정 초안으로 열었습니다. 기존 보관본은 유지됩니다.", () => setMode("edit"))}>이 결과를 수정 초안으로 열기</button></div><Field label="다음 회차 사업연도" value={nextYear} onChange={setNextYear} max={4} /><p className="text-sm leading-7">원본 기획·결과를 남기고 후보·근거·개선점을 복사합니다. 일정·선택 판단·실측·외부 확인 상태는 새로 입력하고 이전 근거·견적·예산 분류는 재확인해야 합니다.</p><button className="region-button" onClick={() => void perform(() => nextEdition(p, result.id, Number(nextYear)), "다음 회차 초안을 만들었습니다. 일정·판단·근거·견적과 예산 분류를 재확인하세요.", () => edit())}>이 결과에서 다음 회차 기획 만들기</button></div><OutcomeReport planning={p} revision={result} /></>}</>}
  </section>;
}
