apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - limitrange.yaml
  - networkpolicy.yaml
  - persistentvolumeclaim.yaml
  - resourcequota.yaml
  - service.yaml
  - serviceaccount.yaml
  - vaultauth.yaml
  - vaultconnection.yaml
  - vaultstaticsecret-harbor-pull.yaml
  - vaultstaticsecret-runtime.yaml
