apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fest-compass-data
  labels:
    app.kubernetes.io/name: fest-compass
    app.kubernetes.io/component: data
    app.kubernetes.io/part-of: fest-compass
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
