apiVersion: v1
kind: ResourceQuota
metadata:
  name: fest-compass
  labels:
    app.kubernetes.io/name: fest-compass
    app.kubernetes.io/part-of: fest-compass
spec:
  hard:
    requests.cpu: "750m"
    requests.memory: 1Gi
    requests.storage: 2Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "3"
    services: "2"
    configmaps: "3"
    secrets: "4"
    persistentvolumeclaims: "1"
