apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: fest-compass-runtime
  labels:
    app.kubernetes.io/name: fest-compass
    app.kubernetes.io/component: runtime-credentials
    app.kubernetes.io/part-of: fest-compass
spec:
  vaultAuthRef: fest-compass
  mount: kv
  type: kv-v2
  path: projects/fest-compass/runtime
  refreshAfter: 1h
  destination:
    name: fest-compass-runtime
    create: true
    transformation:
      excludeRaw: true
      templates:
        TOUR_API_KEY:
          text: |-
            {{- get .Secrets "TOUR_API_KEY" -}}
  rolloutRestartTargets:
    - kind: Deployment
      name: fest-compass
