apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: harbor-pull
  labels:
    app.kubernetes.io/name: fest-compass
    app.kubernetes.io/component: registry-credentials
    app.kubernetes.io/part-of: fest-compass
spec:
  vaultAuthRef: fest-compass
  mount: kv
  type: kv-v2
  path: projects/fest-compass/harbor-pull
  refreshAfter: 1h
  destination:
    name: harbor-pull
    create: true
    type: kubernetes.io/dockerconfigjson
    transformation:
      excludeRaw: true
