import { RegionEvidenceChart } from "./RegionEvidenceChart";
import type { SourceCopy } from "@/lib/planning/types";
import { Availability, CostCharts, ScheduleChart, SourceDetails, VisitComparison } from "../ComparisonCharts";
export function EvidenceView({ source, readOnly = false }: { source: SourceCopy; readOnly?: boolean }) {
  if (source.kind === "comparison") {
    const e = source.value;
    return <div className="space-y-4"><p className="text-sm">{e.context.mode === "archive" ? "과거 회차" : "현재 등록 행사"} · 당시 조회 {e.context.start} ~ {e.context.end} · {e.context.dateRule === "overlap" ? "기간 겹침" : "기간 안 시작"}<br />검색어 {e.context.keyword || "전체"} · 주제 {e.context.theme || "전체"}<br />자료를 담은 시각 {e.savedAt}</p><p className="text-sm">조회 지역 코드: {e.context.regions.join(" · ") || "전체"} · 조회 시각 {e.context.queriedAt || "미확보"}<br />담을 때의 메모: {e.note || "없음"}</p><Availability editions={e.editions} /><ScheduleChart editions={e.editions} /><VisitComparison readOnly={readOnly} editions={e.editions} initialRange={e.selection.kind === "visits" ? e.selection : undefined} /><CostCharts editions={e.editions} />{e.editions.map(d => <div className="region-card" key={d.id}><h4 className="font-bold">{d.year} {d.name}</h4><p className="my-2 text-sm">{d.status} · {d.statusNote}<br />미확인: {d.missing.join(" · ")}</p><SourceDetails source={d.source} />{d.statusSource && <SourceDetails source={d.statusSource} />}</div>)}</div>;
  }
  const e = source.value, r = e.result;
  return <div className="space-y-3 text-sm leading-7"><p>{r.region.provinceName} {r.region.districtName} · 당시 조회 {r.query.start} ~ {r.query.end}<br />자료를 담은 시각 {e.savedAt}</p>{r.resources.items.map(a => <p key={a.id}>{a.title} · {a.address || "주소 미확보"}<br />좌표 {a.longitude ?? "미확보"}, {a.latitude ?? "미확보"}<br />{a.start ? `${a.start} ~ ${a.end}` : "등록 관광자원"} · 기간별 장소 사용은 별도 확인<br />조회 {r.resources.collectedAt}</p>)}{readOnly && <><p>자원 조회 종류 {r.query.kind} · {r.resources.status} · {r.resources.message}<br />표시 {r.resources.items.length}건 / 원천 전체 {r.resources.total ?? "미확보"}건 · {r.resources.pages}쪽 조회<br />방문 이력 {r.history.status} · {r.history.message}</p><RegionEvidenceChart history={r.history} /></>}{!!r.history.points.length && <><p>{r.history.metric} · {r.history.unit}<br />{r.history.message}</p><div className="max-h-80 overflow-auto"><table className="comparison-table"><caption className="text-left">선택 당시 일별 값 · 날짜별 합계를 고유 방문객으로 해석하지 않음</caption><thead><tr><th>날짜</th><th>값</th><th>수집 시각·품질·보관 식별자</th></tr></thead><tbody>{r.history.points.map(p => <tr key={p.date}><td>{p.date}</td><td>{p.value?.toLocaleString("ko-KR") ?? "미확보"}</td><td>{p.collectedAt ?? "미확보"}{readOnly && <span className="block break-all">{p.quality} · {p.snapshotId || "식별자 미확보"}</span>}</td></tr>)}</tbody></table></div></>}<p>담을 때의 메모: {e.note || "없음"}</p><a className="font-bold text-blue underline" target="_blank" rel="noreferrer" href={"resourceId" in e.selection ? r.resources.source : r.history.source}>공공데이터 원천 확인 ↗</a>{readOnly && <p>자원 원천: <a href={r.resources.source} target="_blank" rel="noreferrer" className="underline">공공 관광자원</a> · 방문 원천: <a href={r.history.source} target="_blank" rel="noreferrer" className="underline">지역 방문 이력</a></p>}</div>;
}
