import { day, REGIONS } from "@/lib/region/model";
import { optionIssues, taskStatus } from "@/lib/planning/model";
import { STAGES } from "@/lib/planning/types";
import type { Option, PlanDraft, Stage } from "@/lib/planning/types";

const decision = { undecided: "검토 중", selected: "우선 후보", excluded: "제외 후보" };
const shown = (v: string) => v.trim() || "미정";
export function OptionComparison({ draft: d }: { draft: PlanDraft }) {
  const region = REGIONS.find(r => `${r.provinceCode}/${r.districtCode}` === d.regionKey);
  const rows: [string, (o: Option) => string][] = [["주제", o => shown(o.theme)], ["아이템", o => shown(o.item)], ["참여 대상", o => shown(o.audience)], ["장소", o => shown(o.venue)], ["행사 기간", o => `${shown(o.periods.event.start)} ~ ${shown(o.periods.event.end)}`], ["담당자 가정", o => shown(o.assumptions)], ["제약·미확인", o => shown(o.constraints)], ["판단", o => decision[o.decision]], ["선택·제외 이유", o => shown(o.reason)], ["연결한 근거", o => `${o.links.length}개 연결 · ${new Set(o.links.map(l => l.sourceKey)).size}개 자료`]];
  const periods = d.options.flatMap(o => (Object.keys(STAGES) as Stage[]).flatMap(stage => { const p = o.periods[stage]; return day(p.start) && day(p.end) && p.start <= p.end ? [{ id: o.id, stage, ...p }] : []; }));
  const first = periods.map(p => p.start).sort()[0], last = periods.map(p => p.end).sort().at(-1);
  const dayNo = (v: string) => Date.parse(v) / 86400000;
  const span = first && last ? dayNo(last) - dayNo(first) + 1 : 1;
  return <section className="space-y-5"><header><h2 className="text-2xl font-extrabold">기획 후보 비교</h2><p className="mt-2 text-sm leading-7">{d.year}년 · {region ? `${region.provinceName} ${region.districtName}` : "담당 지역 미정"}<br />{d.options.length < 2 ? "후보 하나는 초안입니다. 다른 안을 추가해 차이를 비교하세요." : `후보 ${d.options.length}개를 같은 항목으로 비교합니다. 첫 후보와 다른 값은 배경색으로 표시합니다.`}</p></header>
    <div className="region-card overflow-x-auto" role="region" aria-label="후보 차이 비교표" tabIndex={0}><table className="comparison-table min-w-[600px]"><caption className="pb-3 text-left text-sm text-muted">작은 화면에서는 표 안을 좌우로 이동할 수 있습니다. 기획 입력·가정이며 자동 추천 순위가 아닙니다.</caption><thead><tr><th>판단 항목</th>{d.options.map(o => <th key={o.id}>{o.name || "이름 미정"}</th>)}</tr></thead><tbody>{rows.map(([label, value]) => <tr key={label}><th className="min-w-28">{label}</th>{d.options.map((o, i) => <td key={o.id} className={`min-w-52 whitespace-pre-wrap break-words ${i > 0 && value(o) !== value(d.options[0]) ? "bg-blue-soft" : ""}`}>{value(o)}</td>)}</tr>)}</tbody></table></div>
    <div className="region-card"><h3 className="text-lg font-extrabold">후보별 설치·행사·철거 일정</h3>{first && last ? <><p className="my-3 text-sm text-muted">{first} ~ {last} · 같은 날짜 축 · 설치(윤곽) / 행사(채움) / 철거(점선)</p><svg viewBox={`0 0 800 ${d.options.length * 105 + 30}`} className="w-full" role="img" aria-label="같은 날짜 축의 후보별 설치·행사·철거 일정"><title>후보 일정 비교 · 아래 표에서 날짜 확인</title>{d.options.map((o, i) => <g key={o.id}><text x="0" y={i * 105 + 18} fontSize="14" fill="#10233d">{(o.name || "미정").slice(0, 30)}</text>{(Object.keys(STAGES) as Stage[]).map((stage, s) => { const p = periods.find(p => p.id === o.id && p.stage === stage); return p ? <g key={stage}><text x="0" y={i * 105 + 42 + s * 24} fontSize="12" fill="#10233d">{STAGES[stage]}</text><rect x={70 + (dayNo(p.start) - dayNo(first)) / span * 720} y={i * 105 + 29 + s * 24} width={Math.max(2, (dayNo(p.end) - dayNo(p.start) + 1) / span * 720)} height="17" rx="3" fill={stage === "event" ? "#2667e8" : "#eaf1ff"} stroke="#2667e8" strokeDasharray={stage === "teardown" ? "4 3" : undefined} /></g> : <text key={stage} x="0" y={i * 105 + 42 + s * 24} fontSize="12">{STAGES[stage]} 미정</text>; })}</g>)}</svg></> : <p className="my-3 text-sm text-muted">유효한 기간을 입력하면 같은 날짜 축에 표시합니다.</p>}<div className="overflow-x-auto"><table className="comparison-table"><thead><tr><th>후보</th>{Object.values(STAGES).map(v => <th key={v}>{v}</th>)}</tr></thead><tbody>{d.options.map(o => <tr key={o.id}><th>{o.name}</th>{(Object.keys(STAGES) as Stage[]).map(s => <td key={s}>{o.periods[s].start || "미정"}<br />~ {o.periods[s].end || "미정"}</td>)}</tr>)}</tbody></table></div><p className="mt-3 text-xs leading-6 text-muted">설치·행사 일부 중첩은 자동 금지하지 않습니다. 장소·시간 충돌 여부를 별도 확인하세요.</p></div>
    <div className="grid gap-4 md:grid-cols-2">{d.options.map(o => { const counts = { done: 0, doing: 0, todo: 0, stale: 0, na: 0 }; o.tasks.forEach(t => { if (taskStatus(o, t).stale) counts.stale++; else if (t.applies === "no") counts.na++; else counts[t.progress]++; }); const labels = { done: "완료", doing: "진행", todo: "미착수", stale: "재확인", na: "해당 없음" }, colors = { done: "#146b61", doing: "#2667e8", todo: "#8a97a8", stale: "#be4b39", na: "#dddfe4" }; return <article key={o.id} className="region-card"><h3 className="font-extrabold">{o.name} · 확인할 항목</h3><ul className="my-3 list-disc space-y-1 pl-5 text-sm">{optionIssues(o).map(issue => <li key={issue}>{issue}</li>)}</ul><p className="text-sm font-bold">준비 과제 진행 기록 {o.tasks.length}개</p>{o.tasks.length > 0 && <><div className="my-3 flex h-4 overflow-hidden rounded-full" role="img" aria-label={Object.entries(counts).map(([k, v]) => `${labels[k as keyof typeof labels]} ${v}개`).join(" · ")}>{Object.entries(counts).map(([k, v]) => <span key={k} style={{ width: `${v / o.tasks.length * 100}%`, background: colors[k as keyof typeof colors] }} />)}</div><p className="text-xs leading-6">{Object.entries(counts).map(([k, v]) => `${labels[k as keyof typeof labels]} ${v}`).join(" · ")}<br />담당 미정 {o.tasks.filter(t => !t.owner.trim()).length} · 기한 미정 {o.tasks.filter(t => !t.due).length} · 적용 미확인 {o.tasks.filter(t => t.applies === "unknown").length}</p></>}<p className="mt-3 text-xs text-muted">업무 진행 개수이며 준비 완료율·안전 승인·예산 산정 결과가 아닙니다.</p></article>; })}</div>
  </section>;
}
