"use client";
import { useState } from "react";
import { currentCheck, newTask, taskBasis, taskStatus, today, uid, venueBasis } from "@/lib/planning/model";
import { CONDITIONS, PROGRESS, REVIEW_STATUS, STAGES, VENUE_STATUS } from "@/lib/planning/types";
import type { Option, ReadinessTask, Stage, TaskReview, VenueCheck } from "@/lib/planning/types";
import { Field, Select } from "./Fields";

export function VenueEditor({ option: o, change }: { option: Option; change: (next: Option, strict?: boolean) => void }) {
  const [stage, setStage] = useState<Stage>("event"), [kind, setKind] = useState<VenueCheck["kind"]>("use"), [status, setStatus] = useState<VenueCheck["status"]>("unknown"), [owner, setOwner] = useState(""), [date, setDate] = useState(today), [reference, setReference] = useState(""), [note, setNote] = useState("");
  return <details className="region-card"><summary className="cursor-pointer text-lg font-extrabold">장소와 기간별 확인</summary><p className="my-4 text-sm leading-7 text-muted">관광자원 등록은 대관 허가가 아닙니다. 설치·행사·철거의 사용과 시설 조건을 각각 확인하세요. 기간·아이템·대상이 바뀌면 이전 기록을 보존하고 현재 조건을 다시 확인합니다.</p>
    <div className="grid gap-3 sm:grid-cols-3">{(Object.keys(STAGES) as Stage[]).map(s => <div key={s} className="rounded-xl bg-paper p-3"><h3 className="mb-3 font-bold">{STAGES[s]} 기간</h3><div className="space-y-3"><Field label={`${STAGES[s]} 시작일`} type="date" value={o.periods[s].start} onChange={start => change({ ...o, periods: { ...o.periods, [s]: { ...o.periods[s], start } } })} /><Field label={`${STAGES[s]} 종료일`} type="date" value={o.periods[s].end} onChange={end => change({ ...o, periods: { ...o.periods, [s]: { ...o.periods[s], end } } })} /></div></div>)}</div>
    <div className="my-4 overflow-x-auto"><table className="comparison-table"><caption className="text-left font-bold">현재 장소·기간·내용에 대한 확인</caption><thead><tr><th>조건</th>{Object.values(STAGES).map(s => <th key={s}>{s}</th>)}</tr></thead><tbody>{Object.entries(CONDITIONS).map(([k, v]) => <tr key={k}><th>{v}</th>{(Object.keys(STAGES) as Stage[]).map(s => <td key={s}>{VENUE_STATUS[currentCheck(o, s, k as VenueCheck["kind"])?.status ?? "unknown"]}</td>)}</tr>)}</tbody></table></div>
    <div className="grid gap-3 sm:grid-cols-3"><Select label="확인 적용 구간" value={stage} onChange={v => setStage(v as Stage)} options={STAGES} /><Select label="확인할 조건" value={kind} onChange={v => setKind(v as VenueCheck["kind"])} options={CONDITIONS} /><Select label="장소 확인 상태" value={status} onChange={v => setStatus(v as VenueCheck["status"])} options={VENUE_STATUS} /><Field label="장소 확인 조직·역할" max={200} value={owner} onChange={setOwner} /><Field label="장소 확인일" type="date" value={date} onChange={setDate} /><Field label="장소 확인 참조" value={reference} onChange={setReference} /></div><div className="my-3"><Field label="사용 조건·확인 메모" value={note} onChange={setNote} multiline /></div>
    <button className="region-button" onClick={() => change({ ...o, venueChecks: [...o.venueChecks, { id: uid(), stage, kind, status, owner, date, reference, note, basis: venueBasis(o, stage) }] }, true)}>장소 확인 기록 추가</button>
    <p className="mt-3 text-xs text-muted">가능·조건부 가능·불가 기록에는 장소, 해당 구간의 시작/종료일, 확인 조직·역할, 확인일과 참조가 필요합니다. 앱의 공식 승인 표시가 아닙니다.</p>
    {!!o.venueChecks.length && <details className="mt-4"><summary className="cursor-pointer font-bold">이전 조건을 포함한 장소 확인 기록 {o.venueChecks.length}개</summary>{o.venueChecks.map(c => { const b = JSON.parse(c.basis); return <div key={c.id} className="my-2 rounded-xl border border-ink/10 p-3 text-sm leading-7"><strong>{STAGES[c.stage]} · {CONDITIONS[c.kind]} · {VENUE_STATUS[c.status]}</strong><p>{b.venue || "장소 미정"} · {b.period.start || "미정"} ~ {b.period.end || "미정"}<br />{c.owner || "담당 미정"} · {c.date || "일자 미정"}<br />참조: {c.reference || "없음"}<br />{c.note}</p>{c.basis !== venueBasis(o, c.stage) && <p className="font-bold text-coral">이전 조건의 기록 · 현재 안은 재확인 필요</p>}</div>; })}</details>}
  </details>;
}

function TaskEditor({ option: o, task: t, change, remove }: { option: Option; task: ReadinessTask; change: (next: ReadinessTask, strict?: boolean) => void; remove: () => void }) {
  const [review, setReview] = useState<TaskReview["status"]>("unknown"), [reviewDate, setReviewDate] = useState(today), [reviewOwner, setReviewOwner] = useState(""), [reviewReference, setReviewReference] = useState("");
  const state = taskStatus(o, t);
  return <details className="rounded-xl border border-ink/15 p-4" open><summary className="cursor-pointer font-bold">{t.title || "새 준비 과제"} · {state.stale ? "재확인 필요" : PROGRESS[t.progress]} · 외부 {REVIEW_STATUS[state.review]}</summary>
    {state.stale && <div className="my-3 rounded-xl bg-coral-soft p-3 text-sm"><p>장소·일정·내용이 달라졌습니다. 이전 완료·외부 확인을 현재 안에 적용하지 않습니다.</p><button className="region-button mt-2" onClick={() => change({ ...t, basis: taskBasis(o), progress: "todo", applies: "unknown", naReason: "", decidedAt: "" })}>현재 안으로 다시 준비</button></div>}
    <div className="my-3 grid gap-3 sm:grid-cols-2"><Field label="과제 이름" max={300} value={t.title} onChange={title => change({ ...t, title })} /><Field label="과제 담당 조직·역할" max={200} value={t.owner} onChange={owner => change({ ...t, owner })} /><Field label="과제 기한" type="date" value={t.due} onChange={due => change({ ...t, due })} /><Field label="필요한 자료 종류" value={t.needed} onChange={needed => change({ ...t, needed })} /><Field label="자료 식별·참조 메모" value={t.reference} onChange={reference => change({ ...t, reference })} /><Select label="과제 적용 여부" value={t.applies} onChange={applies => change({ ...t, applies: applies as ReadinessTask["applies"] })} options={{ unknown: "미확인", yes: "대상", no: "해당 없음" }} />{t.applies === "no" && <><Field label="해당 없음 사유" value={t.naReason} onChange={naReason => change({ ...t, naReason })} /><Field label="해당 없음 판단일" type="date" value={t.decidedAt} onChange={decidedAt => change({ ...t, decidedAt })} /></>}<Select label="과제 진행" value={t.progress} onChange={progress => change({ ...t, progress: progress as ReadinessTask["progress"] })} options={PROGRESS} /></div>
    <fieldset className="my-3"><legend className="text-sm font-bold">선행 과제</legend>{o.tasks.filter(x => x.id !== t.id).map(x => <label className="mr-4 mt-2 inline-flex items-center gap-2 text-sm" key={x.id}><input type="checkbox" checked={t.dependsOn.includes(x.id)} onChange={e => change({ ...t, dependsOn: e.target.checked ? [...t.dependsOn, x.id] : t.dependsOn.filter(id => id !== x.id) })} />{x.title || "이름 미정 과제"}</label>)}{o.tasks.length < 2 && <p className="text-sm text-muted">다른 과제를 추가하면 선택할 수 있습니다.</p>}</fieldset>
    {!!state.blocked.length && <p className="mb-3 text-sm font-bold text-coral">선행 미완료: {state.blocked.map(id => o.tasks.find(x => x.id === id)?.title || "이름 미정").join(" · ")}</p>}
    <Field label="선행 미완료 시 예외 진행 이유" value={t.exceptionReason} onChange={exceptionReason => change({ ...t, exceptionReason })} />
    <details className="mt-4 rounded-xl bg-paper p-3"><summary className="cursor-pointer text-sm font-bold">외부 확인 기록 · 현재 {REVIEW_STATUS[state.review]}</summary><p className="my-3 text-sm text-muted">자료 참조를 적는 것과 외부 확인은 별개입니다. 확인됨은 담당자가 외부 확인 결과를 기록한 상태입니다.</p><div className="grid gap-3 sm:grid-cols-2"><Select label="외부 확인 상태" value={review} onChange={v => setReview(v as TaskReview["status"])} options={REVIEW_STATUS} /><Field label="외부 확인일" type="date" value={reviewDate} onChange={setReviewDate} /><Field label="외부 확인 조직·역할" max={200} value={reviewOwner} onChange={setReviewOwner} /><Field label="외부 확인 참조" value={reviewReference} onChange={setReviewReference} /></div><button className="region-button mt-3" onClick={() => change({ ...t, reviews: [...t.reviews, { id: uid(), status: review, date: reviewDate, owner: reviewOwner, reference: reviewReference, basis: taskBasis(o) }] }, true)}>외부 확인 기록 추가</button>{t.reviews.map(r => <p className="mt-3 break-words text-xs leading-6" key={r.id}>{r.date || "일자 미정"} · {r.owner || "담당 미정"} · {REVIEW_STATUS[r.status]} · {r.reference || "참조 없음"}{r.basis !== taskBasis(o) && " · 이전 조건의 기록"}</p>)}</details>
    <button className="region-button mt-3" disabled={o.tasks.some(x => x.dependsOn.includes(t.id))} onClick={remove}>이 과제 제외</button>{o.tasks.some(x => x.dependsOn.includes(t.id)) && <p className="mt-2 text-xs text-muted">다른 과제의 선행 연결을 먼저 해제하세요.</p>}
  </details>;
}
export function Preparation({ option: o, change }: { option: Option; change: (next: Option, strict?: boolean) => void }) {
  return <details className="region-card"><summary className="cursor-pointer text-lg font-extrabold">준비 과제 {o.tasks.length}개</summary><p className="my-4 text-sm leading-7 text-muted">장소 확인·견적·임차·안전·청소 등 필요한 과제를 기록하세요. 담당·기한 미정, 선행 미완료, 외부 미확인을 구분하며 법정 절차 충족 여부를 자동 판정하지 않습니다.</p><div className="space-y-3">{o.tasks.map(t => <TaskEditor key={t.id} option={o} task={t} change={(next, strict) => change({ ...o, tasks: o.tasks.map(x => x.id === t.id ? next : x) }, strict)} remove={() => change({ ...o, tasks: o.tasks.filter(x => x.id !== t.id) })} />)}</div><button className="region-button mt-4" disabled={o.tasks.length >= 30} onClick={() => change({ ...o, tasks: [...o.tasks, newTask(o)] })}>준비 과제 추가</button></details>;
}
